#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import json
import sys
import os
import random
import string

request = json.load(sys.stdin)

# NETHVOICE_HOST_LOCAL_NETWORKS should be a jason containing local networks [{"network":"192.168.5.0","netmask":"255.255.255.0","gateway":"192.168.5.1"}]
if 'nethvoice_host_local_network' in request:
    agent.set_env('NETHVOICE_HOST_LOCAL_NETWORKS',request['nethvoice_host_local_network'])
else:
    agent.set_env('NETHVOICE_HOST_LOCAL_NETWORKS','{[]}')

if 'conference_url' in request:
    conference_url = request['conference_url']
else:
    conference_url = ' https://meet.jit.si/'
agent.set_env('NETHVOICE_CONFERENCEURL', conference_url)

if 'nethvoice_host' in request:
    agent.set_env('NETHVOICE_HOST', request['nethvoice_host'])
else:
    sys.exit(1)

# Get subscription system id and secret if available
if 'subscription_systemid' in request:
    agent.set_env('SUBSCRIPTION_SYSTEMID', request['subscription_systemid'])
else:
    agent.set_env('SUBSCRIPTION_SYSTEMID', '')

if 'subscription_secret' in request:
    agent.set_env('SUBSCRIPTION_SECRET', request['subscription_secret'])
else:
    agent.set_env('SUBSCRIPTION_SECRET', '')

agent.dump_env()
