#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import json
import sys
import os
import random
import string

request = json.load(sys.stdin)

# NETHVOICE_HOST_LOCAL_NETWORKS should be a jason containing local networks {["network":"192.168.5.0","ip":"192.168.5.14","netmask":"255.255.255.0","gateway":"192.168.5.1"]}
agent.set_env('NETHVOICE_HOST_LOCAL_NETWORKS','{[]}')

if 'conference_url' in request:
    conference_url = request['conference_url']
else:
    conference_url = ' https://meet.jit.si/'
agent.set_env('NETHVOICE_CONFERENCEURL', conference_url)

if 'nethvoice_host' in request:
    agent.set_env('NETHVOICE_HOST', request['nethvoice_host'])
else:
    sys.exit(1)

agent.dump_env()
