#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import json
import sys
import os
import random
import string

# NETHVOICE_HOST_LOCAL_NETWORKS should be a jason containing local networks {["network":"192.168.5.0","ip":"192.168.5.14","netmask":"255.255.255.0","gateway":"192.168.5.1"]}
agent.set_env('NETHVOICE_HOST_LOCAL_NETWORKS','{[]}')

agent.dump_env()
