#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os
import re
import agent
from agent.ldapproxy import Ldapproxy

agent.set_weight(os.path.basename(__file__), 0) # Validation step, no task progress at all

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
request = json.load(sys.stdin)
domain = request.get('user_domain', '')
domparams = Ldapproxy().get_domain(domain)
if not domain or not domparams:
    print('Missing user domain', file=sys.stderr)
    sys.exit(1)

if not 'host' in domparams or domparams['host'] == '' or \
   not 'port' in domparams or domparams['port'] == '' or \
   not 'base_dn' in domparams or not re.search(r'dc=', domparams['base_dn'], re.IGNORECASE) or \
   not 'bind_password' in domparams or domparams['bind_password'] == '' or \
   not 'schema' in domparams or domparams['schema'] == '' or \
   not 'base_dn' in domparams or domparams['base_dn'] == '':
	print('Invalid user domain configuration', file=sys.stderr)
	sys.exit(1)