#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import subprocess
import sys

import agent

agent.set_weight(os.path.basename(__file__), 0)  # Validation step, no task progress at all

request = json.load(sys.stdin)

if "timezone" in request:
    timezone = request["timezone"]
    accepted_timezone_list = set(
        subprocess.check_output(["timedatectl", "list-timezones"], text=True).splitlines()
    )

    if timezone not in accepted_timezone_list:
        agent.set_status("validation-failed")
        json.dump(
            [
                {
                    "field": "timezone",
                    "parameter": "timezone",
                    "value": timezone,
                    "error": "timezone_not_available",
                }
            ],
            fp=sys.stdout,
        )
        sys.exit(2)
