#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys

import agent

request = json.load(sys.stdin)

def getFromRequest(request, var_name, env_name, default = ""):
    if var_name in request:
        agent.set_env(env_name, request[var_name])
    else:
        agent.set_env(env_name, default)

agent.set_env('NETHVOICE_HOST', request.get('nethvoice_host', '').lower())
getFromRequest(request, 'timezone', 'TIMEZONE', 'UTC')

## NethCTI UI
agent.set_env('NETHCTI_UI_HOST', request.get('nethcti_ui_host', '').lower())

# Set APP Brand ID if present in the request, this attribute is only used
# by the migration tool procedure.
# Deprecated, will be removed in future releases.
if "app_brand_id" in request:
    agent.set_env('BRAND_APPID', request['app_brand_id'])
