#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os

import agent

request = json.load(sys.stdin)

# read from  the passwords.env file
passwordsfile = agent.read_envfile("passwords.env")

def getFromRequest(request, var_name, env_name, default = ""):
    if var_name in request:
        agent.set_env(env_name, request[var_name])
    else:
        agent.set_env(env_name, default)

getFromRequest(request, 'nethvoice_host', 'NETHVOICE_HOST', '')
getFromRequest(request, 'nethcti_cdr_script', 'NETHCTI_CDR_SCRIPT', '')
getFromRequest(request, 'nethcti_cdr_script_timeout', 'NETHCTI_CDR_SCRIPT_TIMEOUT', '')
getFromRequest(request, 'nethcti_cdr_script_call_in', 'NETHCTI_CDR_SCRIPT_CALL_IN', '')
getFromRequest(request, 'nethcti_privacy_numbers', 'NETHCTI_PRIVACY_NUMBERS', 'xxx')
getFromRequest(request, 'timezone', 'TIMEZONE', 'UTC')

## NethCTI UI
getFromRequest(request, 'nethcti_ui_host', 'NETHCTI_UI_HOST', '')

## NethVoice adm account for users management
getFromRequest(request, 'nethvoice_adm_username', 'NETHVOICE_USER_PORTAL_USERNAME', '')
passwordsfile['NETHVOICE_USER_PORTAL_PASSWORD'] = request.get('nethvoice_adm_password', "")

## NethVoice Hotel
getFromRequest(request, 'nethvoice_hotel', 'NETHVOICE_HOTEL', 'False')
getFromRequest(request, 'nethvoice_hotel_fias_address', 'NETHVOICE_HOTEL_FIAS_ADDRESS', '')
getFromRequest(request, 'nethvoice_hotel_fias_port', 'NETHVOICE_HOTEL_FIAS_PORT', '')

# Satellite Deepgram and OpenAI api keys
getFromRequest(request, 'satellite_call_transcription_enabled', 'SATELLITE_CALL_TRANSCRIPTION_ENABLED', 'False')
getFromRequest(request, 'satellite_voicemail_transcription_enabled', 'SATELLITE_VOICEMAIL_TRANSCRIPTION_ENABLED', 'False')
passwordsfile['DEEPGRAM_API_KEY'] = request.get('deepgram_api_key', '')
passwordsfile['OPENAI_API_KEY'] = request.get('openai_api_key', '')

# set NETHCTI_CDR_SCRIPT to /usr/share/neth-hotel-fias/cdr.php if nethvoice_hotel_fias_address is set
if request.get('nethvoice_hotel_fias_address', '') != '' and request.get('nethcti_cdr_script', '') == '':
    agent.set_env('NETHCTI_CDR_SCRIPT', '/usr/share/neth-hotel-fias/cdr.php')

# write the passwords.env file
agent.write_envfile("passwords.env", passwordsfile)
