#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

"""
Main routes (without paths) are configured in step 15configure_main_routes
to ensure DNS checks happen before start the actual module configuration.
"""

import os
import sys
import json

import agent

data = json.load(sys.stdin)

# Configure Traefik to route "/tancredi" path requests to the webapp service
agent.set_route({
    'instance': os.environ['MODULE_ID'] + '-tancredi',
    'url':  'http://127.0.0.1:' + os.environ["TANCREDIPORT"] + '/tancredi',
    'http2https':  False,
    'host': os.environ["NETHVOICE_HOST"],
    'path': '/tancredi',
})

# Configure Traefik to route "/provisioning" path requests to get phones configuration
agent.set_route({
    'instance': os.environ['MODULE_ID'] + '-provisioning',
    'url':  'http://127.0.0.1:' + os.environ["TANCREDIPORT"] + '/provisioning',
    'http2https':  False,
    'host': os.environ["NETHVOICE_HOST"],
    'path': '/provisioning',
})

## Set up NethCTI-Server to allow https and websocket connections on same host
agent.set_route({
    'instance': os.environ['MODULE_ID'] + '-server-api',
    'url':  'http://127.0.0.1:' + os.environ["NETHCTI_SERVER_API_PORT"],
    'http2https':  os.environ["TRAEFIK_HTTP2HTTPS"] == "true",
    'host': os.environ["NETHVOICE_HOST"],
    'path': '/webrest',
    'strip_prefix': True,
    'headers': {
        'response': {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Credentials': "true",
            'Access-Control-Allow-Headers': '*'
        }
    }
})

agent.set_route({
    'instance': os.environ['MODULE_ID'] + '-cti-server-api',
    'url':  'http://127.0.0.1:' + os.environ["NETHCTI_SERVER_API_PORT"],
    'http2https':  os.environ["TRAEFIK_HTTP2HTTPS"] == "true",
    'host': os.environ["NETHCTI_UI_HOST"],
    'path': '/webrest',
    'strip_prefix': True,
    'headers': {
        'response': {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Credentials': "true",
            'Access-Control-Allow-Headers': '*'
        }
    }
})


## Set up NethCTI-Server to allow https and websocket connections on same host
agent.set_route({
    'instance': os.environ['MODULE_ID'] + '-server-websocket',
    'url':  'http://127.0.0.1:' + os.environ["NETHCTI_SERVER_WS_PORT"] + '/socket.io',
    'http2https':  os.environ["TRAEFIK_HTTP2HTTPS"] == "true",
    'host': os.environ["NETHCTI_UI_HOST"],
    'path': '/socket.io',
    'headers': {
        'response': {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Credentials': "true",
            'Access-Control-Allow-Headers': '*'
        }
    }
})

## Set up Janus on same host
agent.set_route({
    'instance': os.environ['MODULE_ID'] + '-janus',
    'url':  'http://127.0.0.1:' + os.environ["JANUS_TRANSPORT_PORT"],
    'http2https':  os.environ["TRAEFIK_HTTP2HTTPS"] == "true",
    'host': os.environ["NETHCTI_UI_HOST"],
    'path': '/janus',
    'headers': {
        'response': {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Credentials': "true",
            'Access-Control-Allow-Headers': '*'
        }
    }
})

# CTI Wizard
# Configure middleware API route on NETHVOICE_HOST
agent.set_route({
    'instance': os.environ['MODULE_ID'] + '-middleware-server-api',
    'url':  'http://127.0.0.1:' + os.environ["NETHVOICE_MIDDLEWARE_PORT"],
    'http2https':  os.environ["TRAEFIK_HTTP2HTTPS"] == "true",
    'host': os.environ["NETHVOICE_HOST"],
    'path': '/api',
    'strip_prefix': True,
    'headers': {
        'response': {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Credentials': "true",
            'Access-Control-Allow-Headers': '*'
        }
    }
})

# CTI client
# Configure middleware API route on NETHCTI_UI_HOST 
agent.set_route({
    'instance': os.environ['MODULE_ID'] + '-middleware-cti-server-api',
    'url':  'http://127.0.0.1:' + os.environ["NETHVOICE_MIDDLEWARE_PORT"],
    'http2https':  os.environ["TRAEFIK_HTTP2HTTPS"] == "true",
    'host': os.environ["NETHCTI_UI_HOST"],
    'path': '/api',
    'strip_prefix': True,
    'headers': {
        'response': {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Credentials': "true",
            'Access-Control-Allow-Headers': '*'
        }
    }
})

# Get users admin srv records
ksrv = agent.list_service_providers(agent.redis_connect(use_replica=True), "users-admin", "http", {"domain": data["user_domain"]})

# Check if users admin service is available
if len(ksrv) > 0:

    # Configure Traefik to route "/users-admin" path requests to the user portal service
    agent.set_route({
        'instance': os.environ['MODULE_ID'] + '-users-admin',
        'url': ksrv[0]["url"],
        'http2https':  True,
        'host': os.environ["NETHVOICE_HOST"],
        'path': '/users-admin/' + data["user_domain"],
        'strip_prefix': True,
    })
