#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys

import agent


request = json.load(sys.stdin)
result = agent.run_helper("configure-users-admin", request.get("user_domain", ""))
agent.assert_exp(result.returncode == 0)
