#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import agent.tasks

# Get proxy srv records
proxy_id = agent.resolve_agent_id('nethvoice-proxy@node')
ksrv = agent.list_service_providers(agent.redis_connect(use_replica=True), "sip", "tcp", {"module_id": proxy_id.removeprefix("module/")})

# Configure ICE to enforce the proxy ip address.
agent.set_env("ICEENFORCE", ksrv[0]["address"])
