#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys
import agent
import subprocess

mariadb_root_passwd = os.environ['MARIADB_ROOT_PASSWORD']

request = json.load(sys.stdin)

if 'nethvoice_admin_password' in request:
    # Make sure MariaDB service is started
    result = subprocess.run(["systemctl", "--user", "enable", "--now", "mariadb.service"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    if result.returncode != 0:
        print(f"Failed to start mariadb: {result.stderr}")
        sys.exit(1)
        
    command = [
        "/usr/bin/podman", "exec", "-it", "mariadb",
        "mysql", "-uroot", f"-p{mariadb_root_passwd}", "asterisk",
        "-e",
        f"UPDATE ampusers SET password_sha1 = SHA1('{request['nethvoice_admin_password']}') WHERE username = 'admin';"
    ]

    result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    if result.returncode != 0:
        print(f"Failed to execute command: {result.stderr}")
        sys.exit(1)

sys.exit(0)

