#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

"""
This file is created with separation of resposability in mind.
This configures API segment of reports.
"""

import json
import sys
import os

import agent

# Fetch request
request = json.load(sys.stdin)

# Set environment variables
agent.set_env('REPORTS_INTERNATIONAL_PREFIX', request['reports_international_prefix'])

# Setup traefik routes
# api endpoint
agent.set_route({
    'instance': os.environ['MODULE_ID'] + '-reports-api',
    'url': 'http://127.0.0.1:' + os.environ["REPORTS_API_PORT"],
    'http2https':  os.environ["TRAEFIK_HTTP2HTTPS"] == "true",
    'lets_encrypt': request.get("lets_encrypt", False),
    'host': os.environ["NETHVOICE_HOST"],
    'path': '/pbx-report-api',
    'strip_prefix': True
})
