#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e    # exit immediately if an error occurs
exec 1>&2 # ensure any output is sent to stderr

#restart services if they are already running
RESTART_SERVICES="mariadb.service \
                 freepbx.service \
                 janus.service \
                 nethcti-ui.service \
                 tancredi.service \
                 phonebook.service \
                 reports-api.service \
                 reports-ui.service"

systemctl --user try-restart $RESTART_SERVICES

# If the control reaches this step, the service can be enabled and started

systemctl --user enable --now mariadb.service
systemctl --user enable --now freepbx.service
systemctl --user enable --now janus.service
systemctl --user enable nethcti-server.service # cti server will be started later
systemctl --user enable --now nethcti-ui.service
systemctl --user enable --now tancredi.service
systemctl --user enable --now phonebook.service
systemctl --user enable --now phonebook-update.timer
systemctl --user enable --now watcher.path
# Reports
systemctl --user enable --now reports-api.service
systemctl --user enable --now reports-scheduler.timer
systemctl --user enable --now reports-ui.service
# Satellite
if [ "$SATELLITE_CALL_TRANSCRIPTION_ENABLED" = "True" ]; then
    systemctl --user enable --now satellite.service
    systemctl --user enable --now satellite-mqtt.service
else
    systemctl --user stop satellite.service
    systemctl --user disable satellite.service
    systemctl --user stop satellite-mqtt.service
    systemctl --user disable satellite-mqtt.service
fi