#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

# Update the proxy value for extensions and trunks in the database
MARIADB_ROOT_PASSWORD = agent.read_envfile("passwords.env")["MARIADB_ROOT_PASSWORD"]

# Update the proxy value for extensions
SQL_QUERY = f"""
UPDATE `asterisk`.`sip`
SET `data` = 'sip:{os.environ['PROXY_IP']}:{os.environ['PROXY_PORT']};lr'
WHERE `keyword` = 'outbound_proxy' AND `data` LIKE 'sip:%;lr';
"""
# Update the proxy value for trunks
SQL_QUERY += f"""
UPDATE `asterisk`.`pjsip`
SET `data` = 'sip:{os.environ['PROXY_IP']}:{os.environ['PROXY_PORT']};lr'
WHERE `keyword` = 'outbound_proxy' AND `data` LIKE 'sip:%;lr';
"""

agent.run_helper(*f'podman exec mariadb mysql asterisk -u root -p{MARIADB_ROOT_PASSWORD} -e'.split(), SQL_QUERY).check_returncode()
