#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# wait for FreePBX to be ready

until /usr/bin/podman healthcheck run freepbx > /dev/null ; do
    echo "waiting for FreePBX to be ready" > /dev/stderr
    sleep 5
done