state/asterisk_backup
state/db_backup.xb.gz
state/satellite_postgresql.pg_dump.gz
volumes/agi-bin
volumes/asterisk
volumes/lookup.d
volumes/moh
volumes/pbooksources
volumes/phonebookcsv
volumes/post_scripts
volumes/reports_config
volumes/scripts
volumes/spool
volumes/tancredi
state/passwords.env

state/matrix_postgresql.pg_dump.gz
state/matrix
volumes/matrix-synapse-data
volumes/matrix2acrobits-data/push.backup.db
