#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os

import agent

config = {
    'satellite_call_transcription_enabled': os.getenv('SATELLITE_CALL_TRANSCRIPTION_ENABLED', 'False') == 'True',
    'satellite_voicemail_transcription_enabled': os.getenv('SATELLITE_VOICEMAIL_TRANSCRIPTION_ENABLED', 'False') == 'True',
    'deepgram_api_key': agent.read_envfile("passwords.env").get('DEEPGRAM_API_KEY', ''),
    'openai_api_key': agent.read_envfile("passwords.env").get('OPENAI_API_KEY', ''),
}

json.dump(config, fp=sys.stdout)
