#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

if systemctl --user -q is-active flexisip; then
    install-certificate flexisip && systemctl --user -T try-reload-or-restart flexisip
fi

if systemctl --user -q is-active asterisk; then
    systemctl --user -T try-reload-or-restart asterisk
fi

if systemctl --user -q is-active janus; then
    systemctl --user -T try-reload-or-restart janus
fi
