#!/usr/bin/env bash

# shellcheck disable=SC2034

LOCAL_TESTING_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

POD_NAME="${POD_NAME:-nethvoice-local-test}"
MARIADB_CONTAINER="${MARIADB_CONTAINER:-nethvoice-mariadb}"
FREEPBX_CONTAINER="${FREEPBX_CONTAINER:-nethvoice-freepbx}"
TANCREDI_CONTAINER="${TANCREDI_CONTAINER:-nethvoice-tancredi}"

NETHVOICE_MARIADB_IMAGE="${NETHVOICE_MARIADB_IMAGE:-ghcr.io/nethesis/nethvoice-mariadb:latest}"
NETHVOICE_FREEPBX_IMAGE="${NETHVOICE_FREEPBX_IMAGE:-ghcr.io/nethesis/nethvoice-freepbx:latest}"
NETHVOICE_TANCREDI_IMAGE="${NETHVOICE_TANCREDI_IMAGE:-ghcr.io/nethesis/nethvoice-tancredi:latest}"

APACHE_PORT="${APACHE_PORT:-8080}"
TANCREDIPORT="${TANCREDIPORT:-8081}"
NETHVOICE_MARIADB_PORT="${NETHVOICE_MARIADB_PORT:-3306}"
TIMEZONE="${TIMEZONE:-UTC}"

MARIADB_ROOT_PASSWORD="${MARIADB_ROOT_PASSWORD:-root-test-password}"
AMPDBHOST="${AMPDBHOST:-127.0.0.1}"
AMPDBNAME="${AMPDBNAME:-asterisk}"
AMPDBUSER="${AMPDBUSER:-asteriskuser}"
AMPDBPASS="${AMPDBPASS:-asteriskpass}"
CDRDBUSER="${CDRDBUSER:-cdruser}"
CDRDBPASS="${CDRDBPASS:-cdrpass}"
NETHCTI_DB_USER="${NETHCTI_DB_USER:-ctiuser}"
NETHCTI_DB_PASSWORD="${NETHCTI_DB_PASSWORD:-ctipass}"
PHONEBOOK_DB_NAME="${PHONEBOOK_DB_NAME:-phonebook}"
PHONEBOOK_DB_USER="${PHONEBOOK_DB_USER:-phonebookuser}"
PHONEBOOK_DB_PASS="${PHONEBOOK_DB_PASS:-phonebookpass}"
REPORTS_PASSWORD="${REPORTS_PASSWORD:-reportspass}"

ASTMANAGERPORT="${ASTMANAGERPORT:-5038}"
AMPMGRUSER="${AMPMGRUSER:-admin}"
AMPMGRPASS="${AMPMGRPASS:-ampmanagerpass}"
NETHCTI_AMI_PASSWORD="${NETHCTI_AMI_PASSWORD:-proxyctipass}"
NETHVOICESECRETKEY="${NETHVOICESECRETKEY:-local-test-secret}"
TANCREDI_STATIC_TOKEN="${TANCREDI_STATIC_TOKEN:-local-test-tancredi-token}"
NETHVOICE_HOST="${NETHVOICE_HOST:-127.0.0.1:${TANCREDIPORT}}"
NETHVOICE_PROXY_FQDN="${NETHVOICE_PROXY_FQDN:-127.0.0.1}"
NETHCTI_UI_HOST="${NETHCTI_UI_HOST:-localhost:${APACHE_PORT}}"
ASTERISK_IAX_PORT="${ASTERISK_IAX_PORT:-4569}"
PHONEBOOK_LDAP_PORT="${PHONEBOOK_LDAP_PORT:-636}"
PHONEBOOK_LDAP_USER="${PHONEBOOK_LDAP_USER:-ldapuser}"
PHONEBOOK_LDAP_PASS="${PHONEBOOK_LDAP_PASS:-ldappass}"

FREEPBX_ADMIN_USER="${FREEPBX_ADMIN_USER:-admin}"
FREEPBX_ADMIN_PASSWORD="${FREEPBX_ADMIN_PASSWORD:-adminpass}"
REST_AUTH_USER="${REST_AUTH_USER:-admin}"
REST_API_SECRETKEY="${REST_API_SECRETKEY:-}"

MARIADB_VOLUME="${MARIADB_VOLUME:-mariadb-data}"
TANCREDI_VOLUME="${TANCREDI_VOLUME:-tancredi}"
ASTDB_VOLUME="${ASTDB_VOLUME:-astdb}"

LOCAL_SEED_USERS=(alice bob foo)
LOCAL_SEED_USER_DESCRIPTIONS=(Alice Bob Foo)
LOCAL_SEED_USER_HASHES=(
  '$2a$08$7zExxB/vTDD62/t.DXIVWOMwLaKDiTEI/IP3NctM5iyI85dAuge0y'
  '$2a$08$fT486lE2MOJm4pG.TBPR6u.UrsCFK9IU4Lq6kSaeicZzqR0UWszJu'
  '$2a$08$d63bYGHon6f76mkHGJyB6OGnqOKIwlYi4..gbw9mzXansv6glFoeu'
)
LOCAL_SEED_USER_PASSWORDS=(alicepass bobpass foopass)