#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

request = json.load(sys.stdin)

# read from the passwords.env file
passwordsfile = agent.read_envfile("passwords.env")

def getFromRequest(request, var_name, env_name, default = ""):
    if var_name in request:
        agent.set_env(env_name, request[var_name])
    else:
        agent.set_env(env_name, default)


# Integrations: Deepgram and OpenAI API keys
getFromRequest(request, 'satellite_call_transcription_enabled', 'SATELLITE_CALL_TRANSCRIPTION_ENABLED', 'False')
getFromRequest(request, 'satellite_voicemail_transcription_enabled', 'SATELLITE_VOICEMAIL_TRANSCRIPTION_ENABLED', 'False')
passwordsfile['DEEPGRAM_API_KEY'] = request.get('deepgram_api_key', '')
passwordsfile['OPENAI_API_KEY'] = request.get('openai_api_key', '')

# write the passwords.env file
agent.write_envfile("passwords.env", passwordsfile)
