### UI ###
FROM docker.io/library/node:14.21.2-alpine as node_build
WORKDIR /app
# Install npm dependencies
COPY ui/package.json .
COPY ui/package-lock.json .
RUN --mount=type=cache,id=nethvoice-reports-ui-npm,target=/root/.npm \
    npm ci --cache /root/.npm
# Copy application, clean up and build
COPY ui/public public
COPY ui/src src
COPY ui/.browserslistrc .
COPY ui/.eslintrc.js .
COPY ui/babel.config.js .
COPY ui/vue.config.js .
ENV NODE_ENV=production
RUN rm public/config/config.production.js \
    && npm run build

# From build, copy content in nginx container
FROM docker.io/library/nginx:1.30.3-alpine as ui-production
COPY --from=node_build /app/dist /var/www/html/pbx-report
# Adding production scripts
COPY ui/config-gen.sh /docker-entrypoint.d/99-config-gen.sh
COPY ui/conf.d/ /etc/nginx/conf.d/
RUN chmod +x /docker-entrypoint.d/99-config-gen.sh

### API ###
# Init go builder, installing needed dev packages
FROM docker.io/library/golang:1.19.13-alpine as gobuilder
WORKDIR /app
RUN apk add --no-cache \
        build-base \
        linux-pam-dev \
        pkgconfig \
        rrdtool-dev

# Use gobuilder stage to build api
FROM gobuilder as apibuilder
WORKDIR /app/api
# Download go mod dependencies
COPY api/go.mod .
COPY api/go.sum .
RUN --mount=type=cache,id=nethvoice-reports-api-gomod,target=/go/pkg/mod \
    go mod download
# Build executable
COPY api/ /app/api
RUN --mount=type=cache,id=nethvoice-reports-api-gomod,target=/go/pkg/mod \
    --mount=type=cache,id=nethvoice-reports-api-gobuild,target=/root/.cache/go-build \
    go build

# Use gobuilder stage to build tasks
FROM apibuilder as taskbuilder
WORKDIR /app/tasks
# Download go mod dependencies
COPY tasks/go.mod .
COPY tasks/go.sum .
RUN --mount=type=cache,id=nethvoice-reports-tasks-gomod,target=/go/pkg/mod \
    go mod download
# Build executable
COPY tasks/ /app/tasks
RUN --mount=type=cache,id=nethvoice-reports-tasks-gomod,target=/go/pkg/mod \
    --mount=type=cache,id=nethvoice-reports-tasks-gobuild,target=/root/.cache/go-build \
    go build

# Using alpine as runtime
FROM docker.io/library/alpine:3.17.10 as api-production
# Installing runtime dependencies
RUN apk add --no-cache \
        jq \
        librrd \
        linux-pam-dev \
        mariadb-client \
        openldap-clients \
    && addgroup -g 991 asterisk \
    && adduser -u 990 -G asterisk -s /bin/false -D asterisk
# Adding production scripts
COPY remote-artifacts.sha256 /tmp/remote-artifacts.sha256
ADD https://raw.githubusercontent.com/eficode/wait-for/d48601a8a90c3d22fade68d09b4240739fb44a46/wait-for /usr/bin/wait-for
COPY api/entrypoint.sh /entrypoint
RUN artifact_checksum=$(grep "  /usr/bin/wait-for$" /tmp/remote-artifacts.sha256) \
    && printf "%s\n" "${artifact_checksum}" | sha256sum -c - \
    && chmod +x /usr/bin/wait-for \
    && chmod +x /entrypoint
# Copying executables and setting release environment
ENV GIN_MODE=release
COPY --from=apibuilder /app/api/api /usr/bin/api
COPY --from=taskbuilder /app/tasks/tasks /usr/bin/tasks
COPY root/opt/nethvoice-report /opt/defaults/nethvoice-report
COPY api/ldap-authenticate.sh /usr/bin/ldap-authenticate
RUN chmod +x /usr/bin/ldap-authenticate
ENTRYPOINT [ "/entrypoint" ]
CMD [ "api" ]
