#!/usr/bin/perl

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#
# author: Edoardo Spadoni <edoardo.spadoni@nethesis.it>
#

use strict;
use esmith::Build::CreateLinks qw(:all);

#
# nethvoice-report-update event
#

event_actions('nethvoice-report-update', qw(
	initialize-default-databases 00
	nethvoice-report-conf 50
));

event_templates('nethvoice-report-update', qw(
	/opt/nethvoice-report/api/conf.json
	/etc/httpd/conf.d/default-virtualhost.inc
	/opt/nethvoice-report/scripts/clean-prefix-function.sql
));

event_services('nethvoice-report-update', qw(
	nethvoice-report-api restart
	collectd restart
	httpd reload
));

#
# post-restore-data event
#

event_actions('post-restore-data', qw(
        nethvoice-report-fix-rsync-perms 10
));
