#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# This script is used to grant access to the phonebook database to other modules

import agent
import subprocess

MARIADB_ROOT_PASSWORD = agent.read_envfile("passwords.env")["MARIADB_ROOT_PASSWORD"]
SQL_QUERY = f"RENAME USER 'pbookuser'@'127.0.0.1' TO 'pbookuser';"

# Do not check the return code, the query may fail if the user has already been renamed
subprocess.run(['podman', 'exec', 'mariadb', 'mysql', 'asterisk', '-u', 'root', f'-p{MARIADB_ROOT_PASSWORD}', '-e', SQL_QUERY], capture_output=True)

