#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import agent

with agent.redis_connect() as rdb:
    node_address = rdb.hget(f'node/{int(os.environ["NODE_ID"])}/vpn', 'ip_address')
    instance_name = rdb.get(f"module/{os.environ['MODULE_ID']}/ui_name")

credentials = {
    'host': node_address if node_address else '127.0.0.1',
    'port': int(os.getenv('PHONEBOOK_DB_PORT', '3306')),
    'database': os.getenv('PHONEBOOK_DB_NAME', 'phonebook'),
    'user': os.getenv('PHONEBOOK_DB_USER', 'phonebook'),
    'password': agent.read_envfile("passwords.env").get('PHONEBOOK_DB_PASS',""),
    "instance_name": instance_name if instance_name else "",
    "nethvoice_host": os.environ.get('NETHVOICE_HOST', '')
    }

json.dump(credentials, fp=sys.stdout)
