#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import json
import sys
import os
import subprocess

event = json.load(sys.stdin)
myname = os.environ["NETHVOICE_HOST"]

if not agent.certificate_event_matches(event, myname):
    sys.exit(0) # ignore event if not relevant

# Obtain the changed certificate and its private key
get_proc = agent.run_helper(
    'get-certificate',
    f'--cert-file=server.pem',
    f'--key-file=server.key',
    myname,
)

# Reload the running service if the certificate differs
if get_proc.returncode == 0:
    subprocess.run(['systemctl', '--user', '-T', 'try-reload-or-restart',
        'phonebook.service',
        'janus.service', # XXX: restart just to retain the historical behavior
        'nethcti-server.service', # XXX: restart just to retain the historical behavior
        'nethcti-middleware.service', # XXX: restart just to retain the historical behavior
        # XXX: freepbx.service ignore to retain historical behavior
    ])
