#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os
import subprocess

# Set new service ports
MARIADB_ROOT_PASSWORD = agent.read_envfile("passwords.env")['MARIADB_ROOT_PASSWORD']

ASTERISK_CONFIG_FILES = (
    "/etc/asterisk/pjsip.transports.conf",
    "/etc/asterisk/sip_general_additional.conf",
)


def read_mysql_values(query):
    result = subprocess.run(
        [
            "podman",
            "exec",
            "mariadb",
            "mysql",
            "asterisk",
            "-N",
            "-B",
            "-u",
            "root",
            f"-p{MARIADB_ROOT_PASSWORD}",
            "-e",
            query,
        ],
        check=True,
        stdout=subprocess.PIPE,
        text=True,
    )
    return [value.strip() for value in result.stdout.splitlines() if value.strip()]


def run_freepbx_sed(expression):
    if subprocess.run(
        ["podman", "exec", "freepbx", "true"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    ).returncode == 0:
        subprocess.run(
            ["podman", "exec", "freepbx", "sed", "-i", "-E", expression, *ASTERISK_CONFIG_FILES],
            check=True,
        )
        return

    subprocess.run(
        [
            "podman",
            "run",
            "--rm",
            "--entrypoint",
            "/bin/sed",
            "--volume=asterisk:/etc/asterisk:z",
            os.environ["NETHVOICE_FREEPBX_IMAGE"],
            "-i",
            "-E",
            expression,
            *ASTERISK_CONFIG_FILES,
        ],
        check=True,
    )


def replace_config_ports(old_ports, new_port):
    agent.assert_exp(new_port.isdigit())
    for old_port in sorted(old_ports):
        if old_port != new_port:
            run_freepbx_sed(f"s/:{old_port}$/:{new_port}/")


old_sip_ports = {
    port for port in read_mysql_values("""
SELECT `val`
FROM `kvstore_Sipsettings`
WHERE `key` IN ('udpport-0.0.0.0', 'tcpport-0.0.0.0', 'bindport');
""")
    if port.isdigit()
}
old_sip_ports.update(
    port for port in read_mysql_values("""
SELECT `data`
FROM `sipsettings`
WHERE `keyword` = 'bindport';
""")
    if port.isdigit()
)
old_sips_ports = {
    port for port in read_mysql_values("""
SELECT `val`
FROM `kvstore_Sipsettings`
WHERE `key` IN ('tlsport-0.0.0.0', 'tlsbindport');
""")
    if port.isdigit()
}

replace_config_ports(old_sip_ports, os.environ['ASTERISK_SIP_PORT'])
replace_config_ports(old_sips_ports, os.environ['ASTERISK_SIPS_PORT'])

# SQL query to update kvstore_Sipsettings
SQL_QUERY = f"""
UPDATE `kvstore_Sipsettings`
SET `val` = CASE
    WHEN `key` = 'udpport-0.0.0.0' THEN '{os.environ['ASTERISK_SIP_UDP_PORT']}'
    WHEN `key` = 'tlsport-0.0.0.0' THEN '{os.environ['ASTERISK_SIPS_PORT']}'
    WHEN `key` = 'tcpport-0.0.0.0' THEN '{os.environ['ASTERISK_SIP_PORT']}'
    WHEN `key` = 'bindport' THEN '{os.environ['ASTERISK_SIP_PORT']}'
    WHEN `key` = 'tlsbindport' THEN '{os.environ['ASTERISK_SIPS_PORT']}'
    WHEN `key` = 'rtpstart' THEN '{os.environ['ASTERISK_RTPSTART']}'
    WHEN `key` = 'rtpend' THEN '{os.environ['ASTERISK_RTPEND']}'
END
WHERE `key` IN ('udpport-0.0.0.0', 'tlsport-0.0.0.0', 'tcpport-0.0.0.0', 'bindport', 'tlsbindport', 'rtpstart', 'rtpend');
"""
agent.run_helper(*f'podman exec mariadb mysql asterisk -u root -p{MARIADB_ROOT_PASSWORD} -e'.split(), SQL_QUERY).check_returncode()

# SQL query to update sipsettings RTP range
SQL_QUERY = f"""
UPDATE `sipsettings`
SET `data` = CASE
    WHEN `keyword` = 'rtpstart' THEN '{os.environ['ASTERISK_RTPSTART']}'
    WHEN `keyword` = 'rtpend' THEN '{os.environ['ASTERISK_RTPEND']}'
END
WHERE `keyword` IN ('rtpstart', 'rtpend');
"""
agent.run_helper(*f'podman exec mariadb mysql asterisk -u root -p{MARIADB_ROOT_PASSWORD} -e'.split(), SQL_QUERY).check_returncode()

# SQL query to update freepbx_settings
SQL_QUERY = f"""
UPDATE `freepbx_settings`
SET `value` = '{os.environ['ASTMANAGERPORT']}',
    `name` = 'Asterisk Manager Port',
    `level` = 2,
    `description` = 'Port for the Asterisk Manager',
    `type` = 'int',
    `options` = '1024,65535',
    `defaultval` = '{os.environ['ASTMANAGERPORT']}',
    `readonly` = 1,
    `hidden` = 0,
    `category` = 'Asterisk Manager',
    `module` = '',
    `emptyok` = 0,
    `sortorder` = 0
WHERE `keyword` = 'ASTMANAGERPORT'
"""
agent.run_helper(*f'podman exec mariadb mysql asterisk -u root -p{MARIADB_ROOT_PASSWORD} -e'.split(), SQL_QUERY).check_returncode()

# SQL query to update kvstore_Sipsettings with bindport and tlsbindport
SQL_QUERY = f"""
UPDATE `kvstore_Sipsettings`
SET `val` = CASE
    WHEN `key` = 'bindport' THEN '{os.environ['ASTERISK_SIP_PORT']}'
    WHEN `key` = 'tlsbindport' THEN '{os.environ['ASTERISK_SIPS_PORT']}'
END
WHERE `key` IN ('bindport', 'tlsbindport');
"""
agent.run_helper(*f'podman exec mariadb mysql asterisk -u root -p{MARIADB_ROOT_PASSWORD} -e'.split(), SQL_QUERY).check_returncode()

# SQL query to update iaxsettings
SQL_QUERY = f"""
UPDATE `iaxsettings`
SET `data` = '{os.environ['ASTERISK_IAX_PORT']}'
WHERE `keyword` = 'bindport';
"""
agent.run_helper(*f'podman exec mariadb mysql asterisk -u root -p{MARIADB_ROOT_PASSWORD} -e'.split(), SQL_QUERY).check_returncode()

# SQL query to update sipsettings
SQL_QUERY = f"""
UPDATE `sipsettings`
SET `data` = '{os.environ['ASTERISK_SIP_UDP_PORT']}',
    `seq` = 1,
    `type` = 0
WHERE `keyword` = 'bindport';
"""
agent.run_helper(*f'podman exec mariadb mysql asterisk -u root -p{MARIADB_ROOT_PASSWORD} -e'.split(), SQL_QUERY).check_returncode()

# SQL query to update freepbx_settings for HTTPTLSENABLE
SQL_QUERY = f"""
UPDATE `freepbx_settings`
SET `value` = '0',
    `name` = 'Enable TLS for the mini-HTTP Server',
    `level` = 3,
    `description` = 'Enables listening for HTTPS connections. This is for Asterisk, it is not directly related for FreePBX usage and the value of this setting is irrelevant for accessing core FreePBX settings. Default is no.',
    `type` = 'bool',
    `options` = '',
    `defaultval` = '0',
    `readonly` = 0,
    `hidden` = 0,
    `category` = 'Asterisk Builtin mini-HTTP server',
    `module` = '',
    `emptyok` = 0,
    `sortorder` = 0
WHERE `keyword` = 'HTTPTLSENABLE';
"""
agent.run_helper(*f'podman exec mariadb mysql asterisk -u root -p{MARIADB_ROOT_PASSWORD} -e'.split(), SQL_QUERY).check_returncode()
