#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent


# Cleanup the environment
agent.unset_env('NETHVOICE_USER_PORTAL_USERNAME')
agent.mset_env({
    'NETHVOICE_USER_PORTAL_URL': '',
    'NETHVOICE_USER_PORTAL_NODE': '',
})
agent.unset_env('RESTART_SERVICES')
