#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os
from agent.ldapproxy import Ldapproxy

event = json.load(sys.stdin)

mydomain = os.environ['USER_DOMAIN']
if mydomain not in event.get('domains', []):
    exit(0)

# Get domain parameters
domparams = Ldapproxy().get_domain(mydomain)
agent.set_env('NETHVOICE_LDAP_HOST', domparams['host'])
agent.set_env('NETHVOICE_LDAP_PORT', domparams['port'])
agent.set_env('NETHVOICE_LDAP_USER', domparams['bind_dn'])
agent.set_env('NETHVOICE_LDAP_PASS', domparams['bind_password'])
agent.set_env('NETHVOICE_LDAP_SCHEMA', domparams['schema'])
agent.set_env('NETHVOICE_LDAP_BASE', domparams['base_dn'])

agent.run_helper('systemctl', '--user', 'restart', 'freepbx.service').check_returncode()
agent.run_helper('systemctl', '--user', 'restart', 'phonebook.service').check_returncode()
