#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import agent
import json
import sys
import os
import random
import string

# coma separated port list
port_list = os.environ['TCP_PORTS'].split(",")
agent.set_env('MARIADB_PORT',port_list[0])
agent.set_env('APACHE_PORT',port_list[1])

# Set root password for MariaDB
agent.set_env('MARIADB_ROOT_PASSWORD',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(64)))

# Set DB configuration variables
agent.set_env('AMPDBUSER','freepbxuser')
agent.set_env('AMPDBHOST','localhost')
agent.set_env('AMPDBNAME','asterisk')
agent.set_env('AMPDBENGINE','mysql')
agent.set_env('AMPDBPASS',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(64)))
agent.set_env('CDRDBHOST','localhost')
agent.set_env('CDRDBNAME','asteriskcdrdb')
agent.set_env('CDRDBUSER','cdruser')
agent.set_env('CDRDBPASS',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(64)))

# Set password for Asterisk AMI for FreePBX
agent.set_env('AMPMGRUSER','admin')
agent.set_env('AMPMGRPASS',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(64)))



agent.dump_env()
