#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import agent
import json
import sys
import os
import random
import string

# coma separated port list
port_list = os.environ['TCP_PORTS'].split(",")
agent.set_env('MARIADB_PORT',port_list[0])
agent.set_env('APACHE_PORT',port_list[1])
agent.set_env('ASTMANAGERPORT',port_list[2])
agent.set_env('TANCREDIPORT',port_list[3])
agent.set_env('JANUS_TRANSPORT_PORT',port_list[4])

# Set root password for MariaDB
agent.set_env('MARIADB_ROOT_PASSWORD',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(64)))

# Set DB configuration variables
agent.set_env('AMPDBUSER','freepbxuser')
agent.set_env('AMPDBHOST','127.0.0.1')
agent.set_env('AMPDBNAME','asterisk')
agent.set_env('AMPDBENGINE','mysql')
agent.set_env('AMPDBPASS',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(64)))
agent.set_env('AMPMGRUSER','asterisk')
agent.set_env('AMPMGRPASS',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(64)))
agent.set_env('APACHE_RUN_USER','asterisk')
agent.set_env('APACHE_RUN_GROUP','asterisk')
agent.set_env('AMPASTERISKWEBGROUP','asterisk')
agent.set_env('AMPASTERISKWEBUSER','asterisk')

agent.set_env('BRAND_NAME','NexthVoice')
agent.set_env('BRAND_SITE','http://www.nethvoice.it')
agent.set_env('BRAND_DOCS','http://nethvoice.docs.nethesis.it')

agent.set_env('CDRDBHOST','127.0.0.1')
agent.set_env('CDRDBNAME','asteriskcdrdb')
agent.set_env('CDRDBUSER','cdruser')
agent.set_env('CDRDBPASS',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(64)))

agent.set_env('CTIDBPASS',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(64)))

agent.set_env('TANCREDI_STATIC_TOKEN',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(64)))
agent.set_env('NETHVOICESECRETKEY',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(64)))

agent.set_env('JANUS_ADMIN_SECRET',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(64)))
agent.set_env('JANUS_DEBUG_LEVEL',5)
agent.set_env('RTPSTART',10000)
agent.set_env('RTPEND',15000)
agent.set_env('STUNSERVER','stun1.l.google.com')
agent.set_env('STUNPORT',19302)
agent.set_env('ICEIGNORE','vmnet,tap,tun,virb,vb-')
agent.set_env('LOCAL_IP','172.25.5.83')

agent.dump_env()
