#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e    # exit immediately if an error occurs
exec 1>&2 # ensure any output is sent to stderr

#
# Allow other modules with role pbookreader to read phonebook credentials
#
redis-exec SADD "${AGENT_ID}/roles/pbookreader" "get-phonebook-credentials"

#
# Allow restore-module to submit only the self actions it needs.
#
selfadm_actions=(
    configure-module
    set-integrations
    set-nethvoice-hotel
)
redis-exec SADD "${AGENT_ID}/roles/selfadm" "${selfadm_actions[@]}"
