#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os
import sys

agent.add_public_service(os.environ['MODULE_ID'], [
    os.environ['APACHE_PORT']+"/tcp", # Apache
    os.environ['JANUS_TRANSPORT_PORT']+"/tcp", # Janus
    os.environ['RTPSTART']+"-"+os.environ['RTPEND']+"/tcp", # Janus
    os.environ['NETHCTI_UI_PORT']+"/tcp", # NethCTI UI
])

# Ignore exit code
