#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os

import agent

agent.add_public_service(os.environ['MODULE_ID'], [
    os.environ['APACHE_PORT']+"/tcp", # Apache
    os.environ['JANUS_RTPSTART']+"-"+os.environ['JANUS_RTPEND']+"/udp", # Janus
    os.environ['ASTERISK_RTPSTART']+"-"+os.environ['ASTERISK_RTPEND']+"/udp", # Asterisk
])

# Ignore exit code
