#!/usr/bin/env python3
import os, glob, sys, json, signal, logging, logging.handlers, mysql.connector, argparse, datetime
import pyodbc
import pycurl
import csv
import io
import requests

SYNC_METADATA_SCOPE = 'centralized_phonebook'


def signalHandler(sig, frame):
  logger.critical('interrupted by SIGINT')
  sys.exit(0)

signal.signal(signal.SIGINT, signalHandler)

def getDbConn(config):
  if config['dbtype'] == 'mysql':
    port = unixSocket = None
    try:
      port = int(config['port'])
    except:
      port = None
      unixSocket = config['port']
    try:
      return mysql.connector.connect(host=config['host'], port=port, user=config['user'], password=config['password'], database=config['dbname'],charset='utf8')
    except Exception as err:
      logger.error(str(err))
      return None
  elif(config['dbtype'] == 'mssql'):
    try:
      port = int(config['port'])
      return pyodbc.connect(driver=config['driver'], server=config['host'], port=port, uid=config['user'], pwd=config['password'], database=config['dbname'])
    except Exception as err:
      logger.error(str(err))
      return None

def getPhonebookDestConfig():
  try:
      return {
                "dbtype": "mysql",
                "host": os.environ['PHONEBOOK_DB_HOST'],
                "port": os.environ['PHONEBOOK_DB_PORT'],
                "user": os.environ['PHONEBOOK_DB_USER'],
                "password": os.environ['PHONEBOOK_DB_PASS'],
                "dbname": os.environ['PHONEBOOK_DB_NAME'],
                "dbtable": 'phonebook'
                }
  except Exception as err:
    logger.error(str(err))
    sys.exit(1)

def updateSyncMetadata():
  dConfig = getPhonebookDestConfig()
  dbDest = getDbConn(dConfig)
  if dbDest is None:
    logger.error('destination db connection ("phonebook"): failed while updating sync metadata')
    sys.exit(1)

  curDest = dbDest.cursor()
  try:
    curDest.execute('CREATE TABLE IF NOT EXISTS sync_metadata (scope varchar(255) NOT NULL, last_sync_at datetime DEFAULT NULL, PRIMARY KEY (scope)) ENGINE=MyISAM DEFAULT CHARSET=utf8')
    curDest.execute(
      'INSERT INTO sync_metadata (scope, last_sync_at) VALUES (%s, UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE last_sync_at = UTC_TIMESTAMP()',
      (SYNC_METADATA_SCOPE,)
    )
    dbDest.commit()
    logger.info('updated centralized phonebook sync metadata')
  except Exception as err:
    logger.error('updating centralized phonebook sync metadata failed')
    logger.error(str(err))
    sys.exit(1)
  finally:
    curDest.close()
    dbDest.close()

def syncSourceDB(path, output, deleteonly):
  with open(path, 'r') as sourceFile:
    sConfig = json.load(sourceFile)
  sid = next(iter(sConfig))
  dbSource = getDbConn(sConfig[sid])
  if dbSource is not None:
    logger.debug('source "' + sid + '" connection (' + sConfig[sid]['dbname'] + '): ok')
  else:
    logger.error('source "' + sid + '" connection (' + sConfig[sid]['dbname'] + '): failed')
    sys.exit(1)
  curSource = dbSource.cursor()
  if output == True:
    curSource.execute(sConfig[sid]['query'])
    rows = curSource.fetchall()
    cols = tuple([i[0] for i in curSource.description])
    res = []
    for row in rows:
      temp = {}
      for i, el in enumerate(row):
        temp[cols[i]] = el
      res.append(temp)
    if len(res) == 0:
      temp = {}
      for x in cols:
        temp[x] = ''
      res.append(temp)
    json.dump(res, sys.stdout)
    logger.info('write ' + str(len(rows)) + ' entries to std output')
    logger.info('end ' + ('check of' if output == True else '') + ' source import of ' + path + ' into phonebook.phonebook')
    curSource.close()
    dbSource.close()
    return
  dConfig = getPhonebookDestConfig()
  dbDest = getDbConn(dConfig)
  if dbDest is not None:
    logger.debug('destination db connection ("phonebook"): ok')
  else:
    logger.error('destination db connection ("phonebook"): failed')
    sys.exit(1)
  curDest = dbDest.cursor()
  try:
    delcount = curDest.execute('DELETE FROM ' + dConfig['dbtable'] + ' WHERE sid_imported="{}"'.format(sid))
    logger.info('clean destination: removed ' + str(delcount) + ' entries from ' + dConfig['dbname'] + '.' + dConfig['dbtable'] + ' with sid_imported="' + sid + '"')
    if deleteonly == True:
      return
  except Exception as err:
    logger.error('cleaning destination: removing entries from ' + dConfig['dbname'] + '.' + dConfig['dbtable'] + ' with sid_imported="' + sid + '"')
    logger.error(str(err))
  curSource.execute(sConfig[sid]['query'])
  toTransfer = curSource.rowcount
  curSource.fetchall()

  curSource.close()
  logger.debug('synchronizing source "' + sid + '" (' + str(toTransfer) + ' entries)...')
  start = datetime.datetime.now().replace(microsecond=0)
  sourceCols = list(sConfig[sid]['mapping'].keys())
  destCols = list(sConfig[sid]['mapping'].values())
  destCols.append('sid_imported')

  curSource = dbSource.cursor()
  curSource.execute(sConfig[sid]['query'])
  row=curSource.fetchone()
  importedCount=0
  errCount=0

  if sConfig[sid]['type'] is not None:
    destCols.append('type')
  percents = ('%s, ' * len(destCols))[:-2]

  # Since now row isn't a dict, save columns name to convert it into a dict if it is needed in the while loop
  if(sConfig[sid]['dbtype'] == 'mysql'):
    columns = [col[0] for col in curSource.description]

  while row is not None:
    values = []
    # convert row from tuple to dict if type is mysql
    if(sConfig[sid]['dbtype'] == 'mysql'):
      row = {columns[i]: row[i] for i in range(len(columns))}

    for el in sourceCols:
      if(sConfig[sid]['dbtype'] == 'mysql'):
        values.append(row[el])
      elif(sConfig[sid]['dbtype'] == 'mssql'):
        values.append(row.__getattribute__(el))

    # Append sid_imported
    values.append(str(sid))

    # Append type
    if sConfig[sid]['type'] is not None:
      values.append(str(sConfig[sid]['type']))
    else:
      values.append('custom')

    sql = 'INSERT INTO ' + dConfig['dbtable'] + ' (' + ','.join(destCols) + ') VALUES (' + percents + ')'

    try:
      curDest.execute(sql, tuple(values))
      importedCount += 1
    except Exception as err:
      errCount += 1
      logger.error('copying entry "' + str(row) + '"')
      logger.error(str(err))
    dbDest.commit()
    row = curSource.fetchone()
  end = datetime.datetime.now().replace(microsecond=0)
  percent = str(importedCount*100/toTransfer) if toTransfer > 0 else '0'
  logger.info('source "' + sid + '" imported ' + percent + '%: ' + str(importedCount) + ' imported - ' + str(errCount) + ' errors - ' + str(toTransfer) + ' tot - duration ' + str(end-start))
  curSource.close()
  curDest.close()
  dbSource.close()
  dbDest.close()
  logger.info('end source import of ' + path + ' into phonebook.phonebook')

def extractArgsDbParams(data):
  result = {}
  for arg in data:
    result[arg.split('=')[0]] = arg.split('=')[1]
  return result

def syncSourceCsv(path, output, deleteonly):
  with open(path, 'r') as sourceFile:
    sConfig = json.load(sourceFile)

  sid = next(iter(sConfig))
  crl = pycurl.Curl()

  crl.setopt(crl.URL, str(sConfig[sid]['url']))

  b_obj = io.BytesIO()
  crl.setopt(crl.WRITEFUNCTION, b_obj.write)

  crl.setopt(crl.FAILONERROR, 1)
  crl.setopt(crl.FOLLOWLOCATION, 1)
  crl.setopt(crl.MAXREDIRS, 5)

  try:
    crl.perform()
    s_obj = io.StringIO(b_obj.getvalue().decode('utf-8'))
    logger.debug('source "' + sid + '" connection (' + sConfig[sid]['url'] + '): ok')
  except Exception as err:
    logger.error('source "' + sid + '" connection (' + sConfig[sid]['url'] + '): failed')
    logger.error(str(err))
    sys.exit(1)
  finally:
    crl.close()

  s_obj.seek(0)

  df = []
  sample = s_obj.readline()
  s_obj.seek(0)
  dialect = csv.Sniffer().sniff(sample)
  if (not csv.Sniffer().has_header(sample)):
    logger.warning('CSV doesn\'t have a valid header!')
  csvr = csv.reader(s_obj, dialect=dialect)
  header = next(csvr, None)
  for row in csvr:
    r = {}
    for idx,item in enumerate(row):
        if idx < len(header):
            r[header[idx]] = item
    df.append(r)

  if output == True:
    json.dump(df, sys.stdout)
    logger.info('end ' + ('check of' if output == True else '') + ' source import of ' + path + ' into phonebook.phonebook')
    return

  dConfig = getPhonebookDestConfig()

  dbDest = getDbConn(dConfig)
  if dbDest is not None:
    logger.debug('destination db connection ("phonebook"): ok')
  else:
    logger.error('destination db connection ("phonebook"): failed')
    sys.exit(1)

  curDest = dbDest.cursor()

  try:
    delcount = curDest.execute('DELETE FROM ' + dConfig['dbtable'] + ' WHERE sid_imported="{}"'.format(sid))
    logger.info('clean destination: removed ' + str(delcount) + ' entries from ' + dConfig['dbname'] + '.' + dConfig['dbtable'] + ' with sid_imported="' + sid + '"')
    if deleteonly == True:
      return
  except Exception as err:
    logger.error('cleaning destination: removing entries from ' + dConfig['dbname'] + '.' + dConfig['dbtable'] + ' with sid_imported="' + sid + '"')
    logger.error(str(err))

  toTransfer = len(df)

  logger.debug('synchronizing source "' + sid + '" (' + str(toTransfer) + ' entries)...')

  start = datetime.datetime.now().replace(microsecond=0)

  sourceCols = sConfig[sid]['mapping'].keys()
  destCols = list(sConfig[sid]['mapping'].values())
  destCols.append('sid_imported')

  if sConfig[sid]['type'] is not None:
    destCols.append('type')

  # CSV only: a global owner chosen in the wizard is written to owner_id of every
  # imported row. Skip if owner_id is already mapped.
  owner = sConfig[sid].get('owner')
  writeOwner = bool(owner) and 'owner_id' not in destCols
  if writeOwner:
    destCols.append('owner_id')

  importedCount = 0
  errCount = 0

  percents = ('%s, ' * len(destCols))[:-2]
  for row in df:
    values = []
    for el in sourceCols:
      if el in row:
        values.append(row[el])
      else:
        values.append('')
    values.append(str(sid))
    if sConfig[sid]['type'] is not None:
      values.append(str(sConfig[sid]['type']))
    if writeOwner:
      values.append(str(owner))
    sql = 'INSERT INTO ' + dConfig['dbtable'] + ' (' + ','.join(destCols) + ') VALUES (' + percents + ')'
    try:
      curDest.execute(sql, tuple(values))
      importedCount += 1
    except Exception as err:
      errCount += 1
      logger.error('copying entry "' + str(row) + '"')
      logger.error(str(err))
    dbDest.commit()
  end = datetime.datetime.now().replace(microsecond=0)
  percent = str(importedCount*100/toTransfer) if toTransfer > 0 else '0'
  logger.info('source "' + sid + '" imported ' + percent + '%: ' + str(importedCount) + ' imported - ' + str(errCount) + ' errors - ' + str(toTransfer) + ' tot - duration ' + str(end-start))
  curDest.close()
  dbDest.close()
  logger.info('end source import of ' + path + ' into phonebook.phonebook')

# Sync contacts from the Zucchetti Infinity API into the centralized phonebook.
def normalizeInfinityContact(contact, sid, contact_type):
  row = {}
  name = (contact.get('name') or '').strip()
  if name:
    row['name'] = name
  company = (contact.get('company') or '').strip()
  if company:
    row['company'] = company
  homephone = workphone = cellphone = fax = ''
  for tel in contact.get('tel') or []:
    number = (tel.get('number') or '').strip()
    ptype = (tel.get('type') or '').strip().lower()
    if not number:
      continue
    if 'fax' in ptype and not fax:
      fax = number
    elif ('cell' in ptype or 'mobile' in ptype or 'cellulare' in ptype) and not cellphone:
      cellphone = number
    elif not workphone:
      workphone = number
    elif not homephone:
      homephone = number
  if cellphone:
    row['cellphone'] = cellphone
  if workphone:
    row['workphone'] = workphone
  if homephone:
    row['homephone'] = homephone
  if fax:
    row['fax'] = fax
  primary = secondary = ''
  for mail in contact.get('mail') or []:
    email = (mail.get('mail') or '').strip()
    mtype = (mail.get('type') or '').strip().lower()
    if not email:
      continue
    if mtype == 'primary' and not primary:
      primary = email
    elif mtype == 'secondary' and not secondary:
      secondary = email
    elif not primary:
      primary = email
    elif not secondary:
      secondary = email
  if primary:
    row['workemail'] = primary
  if secondary:
    row['homeemail'] = secondary
  address = (contact.get('address') or '').strip()
  if address:
    row['workstreet'] = address
  office = (contact.get('office') or '').strip()
  if office:
    row['title'] = office
  notes = []
  if contact.get('id'):
    notes.append('Infinity ID: ' + str(contact['id']))
  if office:
    notes.append('Office: ' + office)
  status = (contact.get('status') or '').strip()
  if status:
    notes.append('Status: ' + status)
  if notes:
    row['notes'] = ' | '.join(notes)
  row['type'] = contact_type
  row['sid_imported'] = sid
  return row


def sanitizeInfinityBaseUrl(raw):
  # Be tolerant about what the admin pastes: accept the app base, the home page
  # (.../jsp/home.jsp), any /jsp or /servlet path, missing scheme, trailing slash
  # or a query/fragment, and reduce it to the API base used to build the endpoints.
  url = (raw or '').strip()
  if not url:
    return ''
  if '://' not in url:
    url = 'https://' + url
  for sep in ('?', '#'):
    idx = url.find(sep)
    if idx != -1:
      url = url[:idx]
  low = url.lower()
  cut = len(url)
  for marker in ('/servlet', '/jsp'):
    idx = low.find(marker)
    if idx != -1 and idx < cut:
      cut = idx
  return url[:cut].rstrip('/')


def syncSourceInfinity(path, output, deleteonly):
  with open(path, 'r') as sourceFile:
    sConfig = json.load(sourceFile)
  sid = next(iter(sConfig))
  config = sConfig[sid]
  base_url = sanitizeInfinityBaseUrl(config.get('url'))
  username = config.get('username') or ''
  password = config.get('password') or ''
  # Sharing value (public / group:...) chosen in the wizard, written to every row.
  contact_type = config.get('type') or 'public'
  try:
    if not base_url or not username or not password:
      raise Exception('Infinity source requires a url, username and password')
    token_url = base_url + '/servlet/oauth/token'
    token_response = requests.post(token_url, auth=(username, password), data={'scope': 'logintoken'}, timeout=30)
    if token_response.status_code != 200:
      raise Exception('Failed to get token from ' + token_url + ' with status code ' + str(token_response.status_code))
    token = token_response.json().get('access_token')
    if not token:
      raise Exception('No token found in response from ' + token_url)
    logger.debug('Got bearer token from ' + base_url)
    contact_url = base_url + '/servlet/api/gsfr_fgetaddress_wsapi'
    contact_response = requests.get(contact_url, headers={'Authorization': 'Bearer ' + token}, timeout=120)
    if contact_response.status_code != 200:
      raise Exception('Failed to get contacts from ' + contact_url + ' with status code ' + str(contact_response.status_code))
    contacts = contact_response.json().get('data', [])
    if not isinstance(contacts, list):
      raise Exception('Unexpected response schema from ' + contact_url)
    logger.debug('Got ' + str(len(contacts)) + ' contacts from ' + base_url)
    pb_contacts = [normalizeInfinityContact(c, sid, contact_type) for c in contacts]
    if output == True:
      # check mode: emit a preview to stdout, do not touch the database
      json.dump(pb_contacts[:3], sys.stdout)
      logger.info('end check of source import of ' + path + ' into phonebook.phonebook')
      return
    dConfig = getPhonebookDestConfig()
    dbDest = getDbConn(dConfig)
    if dbDest is None:
      raise Exception('destination db connection ("phonebook"): failed')
    curDest = dbDest.cursor()
    delcount = curDest.execute('DELETE FROM ' + dConfig['dbtable'] + ' WHERE sid_imported="{}"'.format(sid))
    logger.info('clean destination: removed ' + str(delcount) + ' entries from ' + dConfig['dbname'] + '.' + dConfig['dbtable'] + ' with sid_imported="' + sid + '"')
    if deleteonly == True:
      dbDest.commit()
      curDest.close()
      dbDest.close()
      return
    start = datetime.datetime.now().replace(microsecond=0)
    importedCount = 0
    errCount = 0
    for pb_contact in pb_contacts:
      cols = list(pb_contact.keys())
      placeholder = ('%s, ' * len(cols))[:-2]
      sql = 'INSERT INTO ' + dConfig['dbtable'] + ' (' + ','.join(cols) + ') VALUES (' + placeholder + ')'
      try:
        curDest.execute(sql, tuple(pb_contact[c] for c in cols))
        importedCount += 1
      except Exception as err:
        errCount += 1
        logger.error('copying entry "' + str(pb_contact) + '"')
        logger.error(str(err))
      dbDest.commit()
    curDest.close()
    dbDest.close()
    end = datetime.datetime.now().replace(microsecond=0)
    logger.info('source "' + sid + '" imported: ' + str(importedCount) + ' imported - ' + str(errCount) + ' errors - ' + str(len(pb_contacts)) + ' tot - duration ' + str(end-start))
    logger.info('end source import of ' + path + ' into phonebook.phonebook')
  except Exception as err:
    logger.error(str(err))
    sys.exit(1)

if __name__ == '__main__':
  descr = 'MySQL and CSV Phonebook importer. Imports contacts from a MySQL database (or CSV) source into phonebook.phonebook database. Destination log is syslog.'
  parser = argparse.ArgumentParser(description=descr)
  parser.add_argument('source_path', help='absolute path of the source json configuration file')
  parser.add_argument('-lw', '--log_warning', action='store_true', help='enable only warning log messages in syslog')
  parser.add_argument('-lv', '--log_verbose', action='store_true', help='enable debug log level in syslog')
  parser.add_argument('-v', '--verbose', action='store_true', help='enable console debug')
  parser.add_argument('-c', '--check', action='store_true', help='it causes the writing of query results to standard output in JSON format instead of executing the database synchronization. Has more priority than deleteonly')
  parser.add_argument('-d', '--deleteonly', action='store_true', help='just delete entries from this configuration')
  parser.add_argument('--skip-sync-metadata-update', action='store_true', help='skip centralized phonebook sync metadata update after a successful import')
  args = parser.parse_args()
  logger = logging.getLogger(__name__)
  logger.setLevel(logging.DEBUG)
  cHandler = logging.StreamHandler()
  syslogHandler = logging.handlers.SysLogHandler(address = '/dev/log')
  cHandler.setLevel(logging.DEBUG if args.verbose == True else logging.NOTSET)
  syslogHandler.setLevel(logging.INFO if args.log_warning == False else logging.WARNING)
  logFormat = logging.Formatter('[%(process)s] %(levelname)s: %(message)s', datefmt='%d-%b-%y %H:%M:%S')
  cHandler.setFormatter(logFormat)
  syslogHandler.setFormatter(logFormat)
  if args.verbose == True:
    logger.addHandler(cHandler)
  logger.addHandler(syslogHandler)
  if args.source_path:
    logger.info('start ' + ('check of' if args.check == True else '') + ' source import of ' + args.source_path + ' into phonebook.phonebook')
    try:
      logger.debug('reading ' + args.source_path)
      with open(args.source_path, 'r') as sourceFile:
        sConfig = json.load(sourceFile)
    except Exception as err:
      logger.error('reading ' + args.source_path)
      logger.error(str(err))
      sys.exit(1)
    sid = next(iter(sConfig))
    logger.debug(args.source_path + ' has "' + sid + '" source')
    if not sConfig[sid]['enabled']:
      logger.info(sid + ' is disabled')
      sys.exit(0)
    if sConfig[sid]['dbtype'] == 'mysql' or sConfig[sid]['dbtype'] == 'mssql':
      syncSourceDB(args.source_path, args.check, args.deleteonly)
    elif sConfig[sid]['dbtype'] == 'csv':
      syncSourceCsv(args.source_path, args.check, args.deleteonly)
    elif sConfig[sid]['dbtype'] == 'infinity':
        syncSourceInfinity(args.source_path, args.check, args.deleteonly)
    if not args.check and not args.deleteonly and not args.skip_sync_metadata_update:
      updateSyncMetadata()
  else:
    parser.print_help()
