#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os

config = {
    'nethvoice_hotel': os.getenv('NETHVOICE_HOTEL', 'False') == 'True',
    'nethvoice_hotel_fias_address': os.getenv('NETHVOICE_HOTEL_FIAS_ADDRESS', ''),
    'nethvoice_hotel_fias_port': int(os.getenv('NETHVOICE_HOTEL_FIAS_PORT', '')) if os.getenv('NETHVOICE_HOTEL_FIAS_PORT', '').isdigit() else "",
}

json.dump(config, fp=sys.stdout)
