# go builds in centos7
FROM docker.io/library/fedora

WORKDIR /build
COPY . /build

RUN dnf update -y && \
    dnf install -y lz4-devel lz4 git && \
    dnf install -y rpm-build rpmdevtools && \
    dnf install -y npm ruby-devel rvm rbenv

RUN npm install -g yarn grunt-cli

RUN echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
RUN echo 'export PATH="$HOME/.rbenv/shims:$PATH"' >> ~/.bashrc
RUN echo 'eval "$(rbenv init -)"' >> ~/.bashrc
RUN source ~/.bashrc
RUN rbenv install 3.1.0
RUN rbenv global 3.1.0
RUN ruby -v
RUN gem install compass