#!/bin/bash
set -e
exec 1>&2
if [ "${NETHVOICE_MATRIX_ENABLED}" = "True" ]; then
    runagent "${AGENT_INSTALL_DIR}/actions/configure-module/73matrix" <<<'{}'
    systemctl --user try-restart matrix-synapse.service matrix2acrobits.service
fi
