FROM docker.io/library/centos:7.9.2009
WORKDIR /var/lib/asterisk
COPY etc/yum.repos.d/nethserver.repo /etc/yum.repos.d
RUN groupadd -g 991 -r asterisk \
    && useradd -u 990 -r -s /bin/false -d /var/lib/asterisk -M -c 'Asterisk User' -g asterisk asterisk \
    && yum install -y \
        asterisk18-core \
        asterisk18-addons-core \
        asterisk18-dahdi \
        asterisk18-odbc \
        asterisk18-voicemail \
        asterisk18-debuginfo \
        asterisk18-voicemail-odbcstorage \
        unixODBC \
        mysql-connector-odbc \
    && rm -fr /var/cache/yum
COPY --chown=asterisk:asterisk etc/asterisk /etc/asterisk
COPY etc/odbc.ini /etc/odbc.ini
COPY var/lib/asterisk /var/lib/asterisk
RUN chown asterisk:asterisk /var/lib/asterisk/db
COPY entrypoint.sh /entrypoint
ENTRYPOINT [ "/entrypoint" ]
CMD [ "/usr/sbin/asterisk", "-f", "-C", "/etc/asterisk/asterisk.conf" ]
