#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os

import agent


result = agent.run_helper(
    "configure-users-admin",
    os.environ["USER_DOMAIN"],
    "--restart-if-changed",
)
agent.assert_exp(result.returncode == 0)
