#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import agent

# Get proxy srv records
ksrv = agent.list_service_providers(agent.redis_connect(use_replica=True), "users-admin", "http", {"domain": os.environ["USER_DOMAIN"]})

# Configure Traefik to route "/users-admin" path requests to the user portal service
agent.set_route({
    'instance': os.environ['MODULE_ID'] + '-users-admin',
    'url': ksrv[0]["url"],
    'http2https':  True,
    'host': os.environ["NETHVOICE_HOST"],
    'path': '/users-admin/' + os.environ["USER_DOMAIN"],
    'strip_prefix': True,
},
error_passthrough=False
)
