#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

MARIADB_ROOT_PASSWORD=$(grep '^MARIADB_ROOT_PASSWORD=' ./passwords.env) && export $MARIADB_ROOT_PASSWORD

# Check if rooms db needs to be created, exit if already exists
podman exec mariadb /usr/bin/mysql -uroot -p"${MARIADB_ROOT_PASSWORD}" -h 127.0.0.1 -P $NETHVOICE_MARIADB_PORT -BN -e "SHOW DATABASES" | grep -q '^fias$' && exit 0

podman exec -it mariadb bash <<'EOF'
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} -h 127.0.0.1 -P $NETHVOICE_MARIADB_PORT < /docker-entrypoint-initdb.d/00_fias-schema-create.sql ;\
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} -h 127.0.0.1 -P $NETHVOICE_MARIADB_PORT < /docker-entrypoint-initdb.d/40_fias.messages-schema.sql ;\
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} -h 127.0.0.1 -P $NETHVOICE_MARIADB_PORT < /docker-entrypoint-initdb.d/40_fias.messagesparameters-schema.sql ;\
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} -h 127.0.0.1 -P $NETHVOICE_MARIADB_PORT < /docker-entrypoint-initdb.d/40_fias.reservations-schema.sql ;\
/usr/bin/mysql -uroot -p"${MARIADB_ROOT_PASSWORD}" -h 127.0.0.1 -P $NETHVOICE_MARIADB_PORT -e "GRANT ALL on fias.* to '${AMPDBUSER}'@'127.0.0.1' identified by '${AMPDBPASS}'" ;\
exit 0
EOF
