#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import subprocess


subprocess.run([
    os.path.join(os.environ['AGENT_INSTALL_DIR'], 'bin', 'nethvoice-firewall-protection'),
    'remove',
], check=True)
