#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os

import agent

config = {
    'nethvoice_host': os.getenv('NETHVOICE_HOST', ''),
    'nethcti_ui_host': os.getenv('NETHCTI_UI_HOST', ''),
    'lets_encrypt': (agent.get_route(os.environ['MODULE_ID'] + '-wizard') or {}).get('lets_encrypt', False),
    'timezone': os.getenv('TIMEZONE', 'UTC'),
    'user_domain': os.getenv('USER_DOMAIN', ''),
    'reports_international_prefix': os.getenv('REPORTS_INTERNATIONAL_PREFIX', ''),
    'subscription_systemid': os.getenv('SUBSCRIPTION_SYSTEMID', ''),
}

json.dump(config, fp=sys.stdout)
