#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os
import requests

import agent
request = json.load(sys.stdin)

def getFromRequest(request, var_name, env_name, default = ""):
    if var_name in request:
        agent.set_env(env_name, request[var_name])
    else:
        agent.set_env(env_name, default)

# get system id
rdb = agent.redis_connect(privileged=False)
subscription = rdb.hgetall('cluster/subscription')

# check if system has a key
if 'system_id' in subscription:
    key = subscription['system_id']

    # call rebranding api
    url = f'https://my.nethesis.it/api/systems/rebranding/{key}'
    data = requests.get(url).json()

    # check if rebrand is active
    if 'brand' in data:
        getFromRequest(request, 'rebranding_brand_name', 'BRAND_NAME', '')
        getFromRequest(request, 'rebranding_brand_name', 'NETHCTI_UI_PRODUCT_NAME', '')

        getFromRequest(request, 'rebranding_login_people', 'LOGIN_PEOPLE', '')

        getFromRequest(request, 'rebranding_navbar_logo_url', 'NAVBAR_LOGO_URL', '')
        getFromRequest(request, 'rebranding_navbar_logo_dark_url', 'NAVBAR_LOGO_DARK_URL', '')
        getFromRequest(request, 'rebranding_login_logo_url', 'LOGIN_LOGO_URL', '')
        getFromRequest(request, 'rebranding_login_logo_dark_url', 'LOGIN_LOGO_DARK_URL', '')

        getFromRequest(request, 'rebranding_favicon_url', 'FAVICON_URL', '')

        getFromRequest(request, 'rebranding_login_background_url', 'LOGIN_BACKGROUND_URL', '')

        getFromRequest(request, 'rebranding_wizard_brand_name', 'WIZARD_BRAND_NAME', os.getenv('WIZARD_BRAND_NAME', ''))
        getFromRequest(request, 'rebranding_wizard_login_logo_url', 'WIZARD_LOGIN_LOGO_URL', os.getenv('WIZARD_LOGIN_LOGO_URL', ''))
        getFromRequest(request, 'rebranding_wizard_favicon_url', 'WIZARD_FAVICON_URL', os.getenv('WIZARD_FAVICON_URL', ''))
        getFromRequest(request, 'rebranding_wizard_login_background_url', 'WIZARD_LOGIN_BACKGROUND_URL', os.getenv('WIZARD_LOGIN_BACKGROUND_URL', ''))

        getFromRequest(request, 'rebranding_reports_brand_name', 'REPORTS_UI_APP_NAME', 'NethVoice Reports')
        getFromRequest(request, 'rebranding_reports_brand_name', 'REPORTS_UI_BRAND_NAME', 'NethVoice')
        getFromRequest(request, 'rebranding_reports_login_logo_url', 'REPORTS_UI_LOGIN_LOGO_URL', '')
        getFromRequest(request, 'rebranding_reports_favicon_url', 'REPORTS_UI_FAVICON_URL', '')
        getFromRequest(request, 'rebranding_reports_login_background_url', 'REPORTS_UI_LOGIN_BACKGROUND_URL', '')

        getFromRequest(request, 'rebranding_nethlink_company_name', 'NETHCTI_UI_COMPANY_NAME', 'Nethesis')
        getFromRequest(request, 'rebranding_nethlink_company_name', 'NETHCTI_COMPANY_NAME', 'Nethesis')
        getFromRequest(request, 'rebranding_nethlink_company_url', 'NETHCTI_UI_COMPANY_URL', 'https://www.nethesis.it/')
        getFromRequest(request, 'rebranding_nethlink_company_url', 'NETHCTI_COMPANY_URL', 'https://www.nethesis.it/')

        # try to restart the service if needed
        agent.run_helper(*'systemctl --user try-restart nethcti-ui.service'.split()).check_returncode()
        agent.run_helper(*'systemctl --user try-restart reports-ui.service'.split()).check_returncode()
        agent.run_helper(*'systemctl --user try-restart freepbx.service'.split()).check_returncode()