#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os

import agent

request = json.load(sys.stdin)

if "satellite_call_transcription_enabled" in request:
    agent.set_env("SATELLITE_CALL_TRANSCRIPTION_ENABLED", request["satellite_call_transcription_enabled"])
if "satellite_voicemail_transcription_enabled" in request:
    agent.set_env("SATELLITE_VOICEMAIL_TRANSCRIPTION_ENABLED", request["satellite_voicemail_transcription_enabled"])

# read from  the passwords.env file
passwordsfile = agent.read_envfile("passwords.env")

# set DEEPGRAM_API_KEY and OPENAI_API_KEY if present in the request
if 'deepgram_api_key' in request:
    passwordsfile['DEEPGRAM_API_KEY'] = request['deepgram_api_key']

if 'openai_api_key' in request:
    passwordsfile['OPENAI_API_KEY'] = request['openai_api_key']

# write the passwords.env file
agent.write_envfile("passwords.env", passwordsfile)
