# Stage 1: Build Asterisk
FROM docker.io/debian:bullseye-20260518 as builder

# Set fixed Asterisk version
ARG ASTERISK_VERSION=18.26.3
ARG PJSIP_VERSION=2.13.1
ARG DEBIAN_FRONTEND=noninteractive
ARG BUILDROOT=/usr/src/asterisk/build
ARG LIBDIR=/usr/lib
ARG DATADIR=/var/lib
ARG MAKEARGS="DEBUG= OPTIMIZE= DESTDIR=${BUILDROOT} ASTVARRUNDIR=/var/run/asterisk ASTDATADIR=${DATADIR}/asterisk ASTVARLIBDIR=${DATADIR}/asterisk ASTDBDIR=${DATADIR}/asterisk/db NOISY_BUILD=1"
COPY usr/src/asterisk /usr/src/asterisk
RUN apt-get update && \
	apt-get install -y \
		automake \
		build-essential \
		doxygen \
		graphviz \
		libasound2-dev \
		libcap-dev \
		libcurl4-openssl-dev \
		libedit-dev \
		libgcrypt20-dev \
		libgmime-3.0-dev \
		libgsm1-dev \
		libical-dev \
		libjansson-dev \
		libjpeg62-turbo-dev \
		libldap2-dev \
		libltdl-dev \
		liblua5.3-dev \
		libmariadb-dev \
		libncursesw5-dev \
		libneon27-dev \
		libnewt-dev \
		libogg-dev \
		libpopt-dev \
		libpq-dev \
		libpri-dev \
		libresample1-dev \
		libsdl1.2-dev \
		libsdl-image1.2-dev \
		libsensors4-dev \
		libsnmp-dev \
		libspandsp-dev \
		libspeex-dev \
		libspeexdsp-dev \
		libsqlite3-dev \
		libsrtp2-dev \
		libss7-dev \
		libssl-dev \
		libsybdb5 \
		libtiff5-dev \
		libunbound-dev \
		libvorbis-dev \
		libxslt1-dev \
		make \
		ncurses-bin \
		portaudio19-dev \
		unixodbc-dev \
		uuid-dev \
		wget

RUN cd /usr/src/asterisk && \
	wget -O asterisk-${ASTERISK_VERSION}.tar.gz https://downloads.asterisk.org/pub/telephony/asterisk/old-releases/asterisk-${ASTERISK_VERSION}.tar.gz && \
	artifact_checksum=$(grep "  asterisk-${ASTERISK_VERSION}.tar.gz$" remote-artifacts.sha256) && \
	printf "%s\n" "${artifact_checksum}" | sha256sum -c - && \
	tar xzf asterisk-${ASTERISK_VERSION}.tar.gz && \
	rm -f asterisk-${ASTERISK_VERSION}.tar.gz && \
	mkdir cache && \
	cd cache && \
	wget -O pjproject-${PJSIP_VERSION}.tar.bz2 https://raw.githubusercontent.com/asterisk/third-party/master/pjproject/${PJSIP_VERSION}/pjproject-${PJSIP_VERSION}.tar.bz2 && \
	cd .. && \
	artifact_checksum=$(grep "  cache/pjproject-${PJSIP_VERSION}.tar.bz2$" remote-artifacts.sha256) && \
	printf "%s\n" "${artifact_checksum}" | sha256sum -c - && \
	cd asterisk-${ASTERISK_VERSION} && \
	patch -p1 < ../asterisk-18-mp3.patch && \
	patch -p1 < ../lazymembers.patch && \
	mv ../menuselect.make* ./ && \
	perl -pi -e 's/^all:.*$/all:/' sounds/Makefile && \
	perl -pi -e 's/^install:.*$/install:/' sounds/Makefile && \
	mv main/fskmodem.c main/fskmodem.c.old && \
	iconv -f iso-8859-1 -t utf-8 -o main/fskmodem.c main/fskmodem.c.old	&& \
	touch -r main/fskmodem.c.old main/fskmodem.c && \
	rm main/fskmodem.c.old && \
	chmod -x contrib/scripts/dbsep.cgi && \
	export CFLAGS=" -Werror-implicit-function-declaration -DLUA_COMPAT_MODULE -fPIC" && \
	export CXXFLAGS="-Werror-implicit-function-declaration -DLUA_COMPAT_MODULE -fPIC" && \
	export FFLAGS="-Werror-implicit-function-declaration -DLUA_COMPAT_MODULE -fPIC" && \
	export LDFLAGS="-m64 -Wl,--as-needed,--library-path=/usr/lib/x86_64-linux-gnu" && \
	export ASTCFLAGS=" " && \
	sed -i '1s/env python/python3/' contrib/scripts/refcounter.py && \
	./bootstrap.sh && \
	cd menuselect && \
	./configure && \
	cd .. && \
	mkdir -p \
		${BUILDROOT}${DATADIR}/asterisk/.gnupg \
		${BUILDROOT}${DATADIR}/asterisk/agi-bin \
		${BUILDROOT}${DATADIR}/asterisk/db \
		${BUILDROOT}${DATADIR}/asterisk/images \
		${BUILDROOT}${DATADIR}/asterisk/keys/stir_shaken \
		${BUILDROOT}${DATADIR}/asterisk/moh \
		${BUILDROOT}${DATADIR}/asterisk/sounds \
		${BUILDROOT}/var/spool/asterisk/outgoing \
		${BUILDROOT}/var/spool/asterisk/uploads \
		${BUILDROOT}/var/spool/asterisk/cache && \
	./configure --without-imap --with-externals-cache=/usr/src/asterisk/cache --with-gsm=/usr --without-ilbc --with-libedit=yes --with-srtp --with-jansson-bundled --with-pjproject-bundled --with-libjwt-bundled LDFLAGS="${LDFLAGS}" NOISY_BUILD=1 CPPFLAGS="-fPIC" && \
	make menuselect-tree && \
	perl -n -i -e 'print unless /openr2/i' menuselect-tree && \
	make -j"$(nproc)" ${MAKEARGS} && \
	make install ${MAKEARGS} && \
	make samples ${MAKEARGS} && \
	install -D -p -m 0755 apps/app_voicemail_odbc.so ${BUILDROOT}${LIBDIR}/asterisk/modules/app_voicemail_odbc.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/libasteriskssl.so && \
	ln -s libasteriskssl.so.1 ${BUILDROOT}${LIBDIR}/libasteriskssl.so && \
	rm -rf ${BUILDROOT}/etc/asterisk/* && \
	rm -rf ${BUILDROOT}/var/lib/asterisk/phoneprov/* && \
	rm -rf ${BUILDROOT}/tmp && \
	rm -rf ${BUILDROOT}/var/spool/asterisk/voicemail/default && \
	# Remove unused modules
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/app_adsiprog.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/app_festival.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/app_getcpeid.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/app_ices.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/app_image.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/app_jack.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/app_nbscat.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/app_url.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/app_voicemail.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/cdr_sqlite3_custom.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/cel_sqlite3_custom.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/chan_alsa.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/chan_console.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/chan_mgcp.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/chan_oss.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/chan_sip.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/chan_unistim.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/cdr_pgsql.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/cel_pgsql.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/chan_skinny.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/pbx_ael.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/pbx_lua.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_adsi.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_config_pgsql.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_hep.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_hep_rtcp.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_http_post.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_hep_pjsip.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_mwi_external.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_mwi_external_ami.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_pktccops.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_stasis_mailbox.so && \
	cp -a contrib/ast-db-manage ${BUILDROOT}${DATADIR}/asterisk/ast-db-manage && \
	wget -O codec_opus-18.0_1.3.0-x86_64.tar.gz http://downloads.digium.com/pub/telephony/codec_opus/asterisk-18.0/x86-64/codec_opus-18.0_1.3.0-x86_64.tar.gz && \
	artifact_checksum=$(grep "  codec_opus-18.0_1.3.0-x86_64.tar.gz$" ../remote-artifacts.sha256) && \
	printf "%s\n" "${artifact_checksum}" | sha256sum -c - && \
	tar xzf codec_opus-18.0_1.3.0-x86_64.tar.gz --strip-components=1 && \
	wget -O codec_silk-18.0_1.0.3-x86_64.tar.gz http://downloads.digium.com/pub/telephony/codec_silk/asterisk-18.0/x86-64/codec_silk-18.0_1.0.3-x86_64.tar.gz && \
	artifact_checksum=$(grep "  codec_silk-18.0_1.0.3-x86_64.tar.gz$" ../remote-artifacts.sha256) && \
	printf "%s\n" "${artifact_checksum}" | sha256sum -c - && \
	tar xzf codec_silk-18.0_1.0.3-x86_64.tar.gz --strip-components=1 && \
	wget -O codec_siren7-18.0_1.0.7-x86_64.tar.gz http://downloads.digium.com/pub/telephony/codec_siren7/asterisk-18.0/x86-64/codec_siren7-18.0_1.0.7-x86_64.tar.gz && \
	artifact_checksum=$(grep "  codec_siren7-18.0_1.0.7-x86_64.tar.gz$" ../remote-artifacts.sha256) && \
	printf "%s\n" "${artifact_checksum}" | sha256sum -c - && \
	tar xzf codec_siren7-18.0_1.0.7-x86_64.tar.gz --strip-components=1 && \
	wget -O codec_siren14-18.0_1.0.7-x86_64.tar.gz http://downloads.digium.com/pub/telephony/codec_siren14/asterisk-18.0/x86-64/codec_siren14-18.0_1.0.7-x86_64.tar.gz && \
	artifact_checksum=$(grep "  codec_siren14-18.0_1.0.7-x86_64.tar.gz$" ../remote-artifacts.sha256) && \
	printf "%s\n" "${artifact_checksum}" | sha256sum -c - && \
	tar xzf codec_siren14-18.0_1.0.7-x86_64.tar.gz --strip-components=1 && \
	cp *.so ${BUILDROOT}${LIBDIR}/asterisk/modules/ && \
	cp codec_opus_config-en_US.xml ${BUILDROOT}${DATADIR}/asterisk/documentation/thirdparty/

FROM docker.io/library/php:7.4-apache
WORKDIR /var/lib/asterisk
ARG DEBIAN_FRONTEND=noninteractive
RUN groupadd -g 991 -r asterisk && \
    useradd -u 990 -r -s /bin/false -d /var/lib/asterisk -M -c 'Asterisk User' -g asterisk asterisk && \
	apt-get update && \
	apt-get install -y \
		cron \
		curl \
		tdsodbc \
		gettext \
		gnupg \
		jq \
		libldap2-dev \
		libldap-2.4-2 \
		libsodium-dev \
		logrotate \
		mpg123 \
		mycli \
		nodejs \
		npm \
		pip \
		python3-pycurl \
		python3-pyodbc \
		python3-requests \
		sox \
		zip \
		vim \
		supervisor \
		wget \
		odbc-mariadb \
		libjansson4 \
		openssl \
		libxml2 \
		libxslt1.1 \
		libsrtp2-1 \
		libspeex1 \
		libspeexdsp1 \
		libneon27 \
        libpq-dev \
		libspandsp2 \
		libsnmp40 \
		libical3 \
		sqlite3 \
		unixodbc-dev \
		freetds-dev \
		freetds-bin \
		locales \
		libicu-dev

# Enable languages for FreePBX UI (all languages from the dropdown menu)
RUN sed -i 's/^# *bg_BG.UTF-8 UTF-8/bg_BG.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/^# *cs_CZ.UTF-8 UTF-8/cs_CZ.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/^# *de_DE.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/^# *en_GB.UTF-8 UTF-8/en_GB.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/^# *en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/^# *es_ES.UTF-8 UTF-8/es_ES.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/^# *fa_IR.UTF-8 UTF-8/fa_IR.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/^# *fr_FR.UTF-8 UTF-8/fr_FR.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/^# *he_IL.UTF-8 UTF-8/he_IL.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/^# *hu_HU.UTF-8 UTF-8/hu_HU.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/^# *it_IT.UTF-8 UTF-8/it_IT.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/^# *ja_JP.UTF-8 UTF-8/ja_JP.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/^# *nl_NL.UTF-8 UTF-8/nl_NL.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/^# *pt_BR.UTF-8 UTF-8/pt_BR.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/^# *pt_PT.UTF-8 UTF-8/pt_PT.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/^# *ro_RO.UTF-8 UTF-8/ro_RO.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/^# *ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/^# *sv_SE.UTF-8 UTF-8/sv_SE.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/^# *uk_UA.UTF-8 UTF-8/uk_UA.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/^# *vi_VN.UTF-8 UTF-8/vi_VN.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i 's/^# *zh_CN.UTF-8 UTF-8/zh_CN.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen


# Copy Asterisk files
COPY --from=builder /usr/src/asterisk/build/./ /
COPY remote-artifacts.sha256 /tmp/remote-artifacts.sha256
COPY fetch-remote-artifact /usr/local/bin/fetch-remote-artifact

RUN chown asterisk:asterisk \
	/var/lib/asterisk \
	/var/lib/asterisk/.gnupg \
	/var/lib/asterisk/agi-bin \
	/var/lib/asterisk/db \
	/var/lib/asterisk/sounds \
	/var/log/asterisk \
	/var/log/asterisk/cdr-csv \
	/var/log/asterisk/cdr-custom \
	/var/spool/asterisk/ \
	/var/spool/asterisk/monitor \
	/var/spool/asterisk/outgoing \
	/var/spool/asterisk/tmp \
	/var/spool/asterisk/uploads \
	/var/spool/asterisk/voicemail \
	/var/spool/asterisk/cache

RUN mkdir -p /var/lib/asterisk/sounds/nethcti \
    && sh /usr/local/bin/fetch-remote-artifact asterisk-sounds-de.tar.gz https://ns8.ams3.cdn.digitaloceanspaces.com/nethvoice/asterisk-sounds/asterisk-sounds-de.tar.gz \
    && sh /usr/local/bin/fetch-remote-artifact asterisk-sounds-en.tar.gz https://ns8.ams3.cdn.digitaloceanspaces.com/nethvoice/asterisk-sounds/asterisk-sounds-en.tar.gz \
    && sh /usr/local/bin/fetch-remote-artifact asterisk-sounds-es.tar.gz https://ns8.ams3.cdn.digitaloceanspaces.com/nethvoice/asterisk-sounds/asterisk-sounds-es.tar.gz \
    && sh /usr/local/bin/fetch-remote-artifact asterisk-sounds-fr.tar.gz https://ns8.ams3.cdn.digitaloceanspaces.com/nethvoice/asterisk-sounds/asterisk-sounds-fr.tar.gz \
    && sh /usr/local/bin/fetch-remote-artifact asterisk-sounds-it.tar.gz https://ns8.ams3.cdn.digitaloceanspaces.com/nethvoice/asterisk-sounds/asterisk-sounds-it.tar.gz \
    && tar xzf /tmp/asterisk-sounds-de.tar.gz -C /var/lib/asterisk/sounds \
    && tar xzf /tmp/asterisk-sounds-en.tar.gz -C /var/lib/asterisk/sounds \
    && tar xzf /tmp/asterisk-sounds-es.tar.gz -C /var/lib/asterisk/sounds \
    && tar xzf /tmp/asterisk-sounds-fr.tar.gz -C /var/lib/asterisk/sounds \
    && tar xzf /tmp/asterisk-sounds-it.tar.gz -C /var/lib/asterisk/sounds \
    && rm -f /tmp/asterisk-sounds-*.tar.gz \
    && chown -R asterisk:asterisk /var/lib/asterisk/sounds

COPY --chown=asterisk:asterisk etc/asterisk /etc/asterisk
COPY etc/odbc.ini /etc/odbc.ini
COPY etc/odbcinst.ini /etc/odbcinst.ini
COPY var/lib/asterisk /var/lib/asterisk
COPY usr/bin/backup_astdb /usr/bin/backup_astdb
COPY usr/bin/restore_astdb /usr/bin/restore_astdb
COPY usr/local/bin/import-certificate /usr/local/bin/import-certificate
COPY usr/lib/asterisk/modules/codec_g729.so /usr/lib/asterisk/modules/codec_g729.so

RUN mkdir -p \
	/etc/phonebook/sources.d/ \
	/var/lib/asterisk/playback \
	/var/run/asterisk/ \
	/var/run/nethvoice/ \
	/var/www/html/freepbx/admin/modules/framework

# Download framework module
RUN sh /usr/local/bin/fetch-remote-artifact freepbx-framework-bootstrap-release-16.0.39.tar.gz https://github.com/FreePBX/framework/archive/refs/tags/release/16.0.39.tar.gz && \
	tar xzf /tmp/freepbx-framework-bootstrap-release-16.0.39.tar.gz --strip-components=1 -C /var/www/html/freepbx/admin/modules/framework && \
	rm -f /tmp/freepbx-framework-bootstrap-release-16.0.39.tar.gz && \
	cp -a /var/www/html/freepbx/admin/modules/framework/amp_conf/htdocs/* /var/www/html/freepbx/ && \
	cp /var/www/html/freepbx/admin/modules/framework/amp_conf/astetc/enum.conf /etc/asterisk/ && \
	cp /var/www/html/freepbx/admin/modules/framework/amp_conf/astetc/musiconhold.conf /etc/asterisk/ && \
	cp /var/www/html/freepbx/admin/modules/framework/amp_conf/astetc/phpagi.conf /etc/asterisk/ && \
	cp /var/www/html/freepbx/admin/modules/framework/amp_conf/astetc/privacy.conf /etc/asterisk/ && \
	cp /var/www/html/freepbx/admin/modules/framework/amp_conf/astetc/queues.conf /etc/asterisk/ && \
	cp /var/www/html/freepbx/admin/modules/framework/amp_conf/astetc/ucc_restrict.conf /etc/asterisk/ && \
	cp -a /var/www/html/freepbx/admin/modules/framework/amp_conf/agi-bin /var/lib/asterisk/ && \
	cp -a /var/www/html/freepbx/admin/modules/framework/amp_conf/bin /var/lib/asterisk/

# Download other modules
RUN install_module() { \
		module_url="${2}"; \
		module_archive="${1}-${module_url##*/}"; \
		module_dir="/var/www/html/freepbx/admin/modules/${1}"; \
		mkdir -p "${module_dir}" && \
		sh /usr/local/bin/fetch-remote-artifact "${module_archive}" "${module_url}" && \
		tar xzf "/tmp/${module_archive}" --strip-components=1 -C "${module_dir}" && \
		rm -f "/tmp/${module_archive}"; \
	}; \
	install_module announcement https://github.com/FreePBX/announcement/archive/refs/tags/release/16.0.7.tar.gz && \
	install_module arimanager https://github.com/FreePBX/arimanager/archive/refs/tags/release/16.0.13.tar.gz && \
	install_module asterisk-cli https://github.com/FreePBX/asterisk-cli/archive/refs/tags/release/16.0.8.tar.gz && \
	install_module asteriskinfo https://github.com/FreePBX/asteriskinfo/archive/refs/tags/release/16.0.10.tar.gz && \
	install_module backup https://github.com/FreePBX/backup/archive/refs/tags/release/16.0.70.3.tar.gz && \
	install_module blacklist https://github.com/FreePBX/blacklist/archive/refs/tags/release/16.0.21.tar.gz && \
	install_module bulkhandler https://github.com/FreePBX/bulkhandler/archive/refs/tags/release/16.0.16.tar.gz && \
	install_module calendar https://github.com/FreePBX/calendar/archive/refs/tags/release/16.0.34.2.tar.gz && \
	install_module callback https://github.com/FreePBX/callback/archive/refs/tags/release/16.0.4.tar.gz && \
	install_module callforward https://github.com/FreePBX/callforward/archive/refs/tags/release/16.0.6.tar.gz && \
	install_module callrecording https://github.com/FreePBX/callrecording/archive/refs/tags/release/16.0.22.tar.gz && \
	install_module callwaiting https://github.com/FreePBX/callwaiting/archive/refs/tags/release/16.0.5.tar.gz && \
	install_module cdr https://github.com/FreePBX/cdr/archive/refs/tags/release/16.0.46.27.tar.gz && \
	install_module cel https://github.com/FreePBX/cel/archive/refs/tags/release/16.0.20.tar.gz && \
	install_module certman https://github.com/FreePBX/certman/archive/refs/tags/release/16.0.30.tar.gz && \
	install_module conferences https://github.com/FreePBX/conferences/archive/refs/tags/release/16.0.9.tar.gz && \
	install_module customappsreg https://github.com/FreePBX/customappsreg/archive/refs/tags/release/16.0.5.tar.gz && \
	install_module daynight https://github.com/FreePBX/daynight/archive/refs/tags/release/16.0.3.tar.gz && \
	install_module dashboard https://github.com/FreePBX/dashboard/archive/refs/tags/release/16.0.21.tar.gz && \
	install_module disa https://github.com/FreePBX/disa/archive/refs/tags/release/16.0.5.tar.gz && \
	install_module donotdisturb https://github.com/FreePBX/donotdisturb/archive/refs/tags/release/16.0.3.tar.gz && \
	install_module fax https://github.com/FreePBX/fax/archive/refs/tags/release/16.0.13.tar.gz && \
	install_module featurecodeadmin https://github.com/FreePBX/featurecodeadmin/archive/refs/tags/release/16.0.11.tar.gz && \
	install_module filestore https://github.com/FreePBX/filestore/archive/refs/tags/release/16.0.18.5.tar.gz && \
	install_module findmefollow https://github.com/FreePBX/findmefollow/archive/refs/tags/release/16.0.23.tar.gz && \
	install_module framework https://github.com/FreePBX/framework/archive/refs/tags/release/16.0.40.3.tar.gz && \
	install_module iaxsettings https://github.com/FreePBX/iaxsettings/archive/refs/tags/release/16.0.4.tar.gz && \
	install_module infoservices https://github.com/FreePBX/infoservices/archive/refs/tags/release/16.0.2.tar.gz && \
	install_module ivr https://github.com/FreePBX/ivr/archive/refs/tags/release/16.0.10.tar.gz && \
	install_module languages https://github.com/FreePBX/languages/archive/refs/tags/release/16.0.4.tar.gz && \
	install_module logfiles https://github.com/FreePBX/logfiles/archive/refs/tags/release/16.0.7.tar.gz && \
	install_module manager https://github.com/FreePBX/manager/archive/refs/tags/release/16.0.24.tar.gz && \
	install_module miscapps https://github.com/FreePBX/miscapps/archive/refs/tags/release/16.0.2.tar.gz && \
	install_module music https://github.com/FreePBX/music/archive/refs/tags/release/16.0.3.tar.gz && \
	install_module outroutemsg https://github.com/FreePBX/outroutemsg/archive/refs/tags/release/16.0.1.tar.gz && \
	install_module parking https://github.com/FreePBX/parking/archive/refs/tags/release/16.0.4.tar.gz && \
	install_module pm2 https://github.com/FreePBX/pm2/archive/refs/tags/release/14.0.1.tar.gz && \
	install_module queueprio https://github.com/FreePBX/queueprio/archive/refs/tags/release/16.0.3.tar.gz && \
	install_module ringgroups https://github.com/FreePBX/ringgroups/archive/refs/tags/release/16.0.11.tar.gz && \
	install_module setcid https://github.com/FreePBX/setcid/archive/refs/tags/release/16.0.3.tar.gz && \
	install_module sipsettings https://github.com/FreePBX/sipsettings/archive/refs/tags/release/16.0.27.tar.gz && \
	install_module soundlang https://github.com/FreePBX/soundlang/archive/refs/tags/release/16.0.9.tar.gz && \
	install_module timeconditions https://github.com/FreePBX/timeconditions/archive/refs/tags/release/16.0.11.tar.gz && \
	install_module userman https://github.com/FreePBX/userman/archive/refs/tags/release/16.0.44.20.tar.gz && \
	install_module vmblast https://github.com/FreePBX/vmblast/archive/refs/tags/release/16.0.11.tar.gz && \
	install_module bosssecretary https://github.com/nethesis/freepbx-bosssecretary/archive/refs/tags/1.0.1.tar.gz && \
	mkdir -p /var/www/html/freepbx/admin/modules/core && \
	rm -fr /var/www/html/freepbx/admin/modules/core/* && \
	install_module core https://github.com/nethesis/freepbx-core/archive/refs/tags/release/ns8/16.0.68.9-pl.2.tar.gz && \
	install_module customcontexts https://github.com/nethesis/freepbx-customcontexts/archive/refs/tags/release/13.0.3.4.tar.gz && \
	install_module directdid https://github.com/nethesis/directdid/archive/1.1.8.tar.gz && \
	install_module extraoptions https://github.com/nethesis/freepbx-extraoptions/archive/refs/tags/1.0.0.tar.gz && \
	install_module googletts https://github.com/nethesis/googletts/archive/refs/tags/0.0.3.tar.gz && \
	install_module nethdash https://github.com/nethesis/nethdash/archive/1.0.tar.gz && \
	install_module paging https://github.com/nethesis/freepbx-paging/archive/refs/tags/release/ns8/16.0.11-pl.2.tar.gz && \
	install_module queueexit https://github.com/nethesis/queueexit/archive/0.0.1.tar.gz && \
	install_module queuemetrics https://github.com/nethesis/queuemetrics/archive/refs/tags/release/2.11.0.3.tar.gz && \
	install_module queues https://github.com/nethesis/freepbx-queues/archive/refs/tags/release/16.0.28.tar.gz && \
	install_module rapidcode https://github.com/nethesis/RapidCode/archive/refs/tags/1.0.1.tar.gz && \
	install_module recordings https://github.com/nethesis/freepbx-recordings/archive/refs/tags/release/ns8/16.0.14-pl.2.tar.gz && \
	install_module returnontransfer https://github.com/nethesis/returnontransfer/archive/refs/tags/1.1.11.tar.gz && \
	install_module voicemail https://github.com/nethesis/freepbx-voicemail/archive/14.0.6.26.tar.gz

# Install Nethesis vendor modules
COPY --chown=asterisk:asterisk var/www/html/freepbx/admin/modules/nethcqr /var/www/html/freepbx/admin/modules/nethcqr
COPY --chown=asterisk:asterisk var/www/html/freepbx/admin/modules/nethcti3 /var/www/html/freepbx/admin/modules/nethcti3
COPY --chown=asterisk:asterisk var/www/html/freepbx/admin/modules/nethhotel /var/www/html/freepbx/admin/modules/nethhotel
COPY --chown=asterisk:asterisk var/www/html/freepbx/admin/modules/pin /var/www/html/freepbx/admin/modules/pin
COPY --chown=asterisk:asterisk var/www/html/freepbx/admin/modules/queueoptions /var/www/html/freepbx/admin/modules/queueoptions
COPY --chown=asterisk:asterisk var/www/html/freepbx/admin/modules/recallonbusy /var/www/html/freepbx/admin/modules/recallonbusy
COPY usr/sbin/recallonbusy /usr/sbin/recallonbusy
COPY --chown=asterisk:asterisk var/www/html/freepbx/admin/modules/satellite /var/www/html/freepbx/admin/modules/satellite
COPY --chown=asterisk:asterisk var/www/html/freepbx/admin/modules/visualplan /var/www/html/freepbx/admin/modules/visualplan

# Remove tests and development files
RUN rm -rf /var/www/html/freepbx/admin/modules/satellite/tests && \
	rm -rf /var/www/html/freepbx/admin/modules/satellite/AGENTS.md


# Create directories
RUN mkdir -p \
	/var/lib/asterisk/bin/backup \
	/var/log/asterisk \
	/var/www/html/freepbx/admin/assets/ \
	/var/www/html/freepbx/admin/assets/less/cache \
	/var/www/html/freepbx/admin/brand/ \
	/var/www/html/freepbx/admin/modules/asteriskinfo/assets/less/cache \
	/var/www/html/freepbx/admin/modules/backup/assets/less/cache \
	/var/www/html/freepbx/admin/modules/blacklist/assets/less/cache \
	/var/www/html/freepbx/admin/modules/bulkhandler/assets/less/cache \
	/var/www/html/freepbx/admin/modules/calendar/assets/less/cache \
	/var/www/html/freepbx/admin/modules/cdr/assets/less/cache \
	/var/www/html/freepbx/admin/modules/cdr/ucp/assets/less/cache \
	/var/www/html/freepbx/admin/modules/cel/assets/less/cache \
	/var/www/html/freepbx/admin/modules/cel/ucp/assets/less/cache \
	/var/www/html/freepbx/admin/modules/certman/assets/less/cache \
	/var/www/html/freepbx/admin/modules/conferences/assets/less/cache \
	/var/www/html/freepbx/admin/modules/core/assets/less/cache \
	/var/www/html/freepbx/admin/modules/core/assets/less/ampusers/cache \
	/var/www/html/freepbx/admin/modules/core/assets/less/devices/cache \
	/var/www/html/freepbx/admin/modules/core/assets/less/did/cache \
	/var/www/html/freepbx/admin/modules/core/assets/less/extensions/cache \
	/var/www/html/freepbx/admin/modules/core/assets/less/routing/cache \
	/var/www/html/freepbx/admin/modules/core/assets/less/trunks/cache \
	/var/www/html/freepbx/admin/modules/core/assets/less/users/cache \
	/var/www/html/freepbx/admin/modules/core/logs \
	/var/www/html/freepbx/admin/modules/customappsreg/assets/less/cache \
	/var/www/html/freepbx/admin/modules/customappsreg/assets/less/customdests/cache \
	/var/www/html/freepbx/admin/modules/customappsreg/assets/less/customextens/cache \
	/var/www/html/freepbx/admin/modules/dashboard/assets/less/cache \
	/var/www/html/freepbx/admin/modules/featurecodeadmin/assets/less/cache \
	/var/www/html/freepbx/admin/modules/filestore/assets/less/cache \
	/var/www/html/freepbx/admin/modules/ivr/assets/less/cache \
	/var/www/html/freepbx/admin/modules/music/assets/less/cache \
	/var/www/html/freepbx/admin/modules/pm2/node/logs \
	/var/www/html/freepbx/admin/modules/pm2/node/node_modules \
	/var/www/html/freepbx/admin/modules/queueprio/assets/less/cache \
	/var/www/html/freepbx/admin/modules/recordings/assets/less/cache \
	/var/www/html/freepbx/admin/modules/soundlang/assets/less/cache \
	/var/www/html/freepbx/admin/modules/userman/assets/less/cache \
	/var/www/html/freepbx/admin/modules/vmblast/assets/less/cache \
	/var/www/html/freepbx/admin/modules/voicemail/assets/less/cache \
	/var/www/html/freepbx/admin/modules/voicemail/ucp/assets/less/cache \
	/var/www/html/freepbx/admin/images/ \
	/initdb.d

# Fix permissions
RUN chown -R asterisk:asterisk \
	/etc/phonebook/sources.d/ \
	/var/log/asterisk \
	/var/lib/asterisk/.gnupg \
	/var/lib/asterisk/agi-bin \
	/var/lib/asterisk/playback \
	/var/lib/asterisk/bin/backup \
	/var/run/asterisk/ \
	/var/run/nethvoice/ \
	/var/www/html/freepbx/admin/assets/ \
	/var/www/html/freepbx/admin/assets/less/cache \
	/var/www/html/freepbx/admin/images/ \
	/var/www/html/freepbx/admin/modules/core/logs \
	/var/www/html/freepbx/admin/modules/pm2/node/logs \
	/var/www/html/freepbx/admin/modules/pm2/node/node_modules \
	/var/www/html/freepbx/admin/modules/*/assets/less/cache \
	/var/www/html/freepbx/admin/modules/*/ucp/assets/less/cache \
	/var/www/html/freepbx/admin/modules/*/assets/less/*/cache

RUN chown asterisk:asterisk \
	/var/lib/asterisk \
	/var/lib/asterisk/bin \
	/var/www/html/freepbx/admin/assets/js/

# Direct links to modules
RUN ln -s /var/www/html/freepbx/admin/modules/visualplan/htdocs /var/www/html/freepbx/visualplan \
	&& ln -s /var/www/html/freepbx/admin/modules/nethhotel/htdocs /var/www/html/freepbx/hotel


# Link all mudule assets directories
RUN for asset in $(find /var/www/html/freepbx/admin/modules/ -type d -name assets); do \
	module=$(echo $asset | cut -d'/' -f8); \
	ln -s $asset /var/www/html/freepbx/admin/assets/$module; \
done

# Replace FreepBX cron implementation with noop
COPY var/www/html/freepbx/admin/libraries/BMO/Cron.class.php /var/www/html/freepbx/admin/libraries/BMO/Cron.class.php

# Add branding
COPY var/www/html/freepbx/admin/brand/* /var/www/html/freepbx/admin/brand/

RUN ln -sf /var/lib/asterisk/bin/fwconsole /usr/bin/fwconsole

RUN pip install mysql-connector-python configparser


# Use PHP development ini configuration and enable logging on syslog
COPY usr/local/etc/php/php.ini /usr/local/etc/php/php.ini

# create link to library for building php pdo_dblib
RUN ln -s /usr/lib/x86_64-linux-gnu/libsybdb.so /usr/lib/libsybdb.so

# Install php additional modules
RUN docker-php-source extract && \
	docker-php-ext-configure pdo_mysql && docker-php-ext-install pdo_mysql && \
	docker-php-ext-configure gettext && docker-php-ext-install gettext && \
	ln -s /usr/lib/x86_64-linux-gnu/libldap.so /usr/lib/libldap.so && docker-php-ext-configure ldap && docker-php-ext-install ldap && \
	docker-php-ext-configure sysvsem && docker-php-ext-install sysvsem && \
	docker-php-ext-configure pdo_odbc --with-pdo-odbc=unixODBC,/usr && docker-php-ext-install pdo_odbc && \
	docker-php-ext-configure sockets && docker-php-ext-install sockets && \
	docker-php-ext-configure pdo_dblib && docker-php-ext-install pdo_dblib && \
    docker-php-ext-configure pdo_pgsql && docker-php-ext-install pdo_pgsql && \
	docker-php-ext-configure intl && docker-php-ext-install intl && \
	docker-php-source delete

# Install nethvoice-wizard-restapi and nethvoice-wizard-ui
COPY var/www/html/freepbx/rest /var/www/html/freepbx/rest
COPY wizard-ui /tmp/wizard
RUN --mount=type=cache,id=nethvoice-freepbx-composer,target=/var/cache/composer \
	--mount=type=cache,id=nethvoice-freepbx-npm,target=/root/.npm \
	--mount=type=cache,id=nethvoice-freepbx-yarn,target=/var/cache/yarn \
	cd /var/www/html/freepbx/rest/ && \
	sh /usr/local/bin/fetch-remote-artifact composer-2.9.8.phar https://getcomposer.org/download/2.9.8/composer.phar && \
	mv /tmp/composer-2.9.8.phar composer.phar && \
	COMPOSER_CACHE_DIR=/var/cache/composer COMPOSER_ALLOW_SUPERUSER=1 php composer.phar install --no-dev && \
	rm -fr README.md composer.json composer.lock composer.phar test && \
	cd /tmp/wizard && \
	npm_config_cache=/root/.npm npx -y -p npm@6 npm install yarn && node_modules/yarn/bin/yarn install --cache-folder /var/cache/yarn && node_modules/grunt-cli/bin/grunt build && \
	mkdir -p /var/www/html/freepbx/wizard && \
	cp -r dist/* /var/www/html/freepbx/wizard/ && \
	rm -fr /tmp/wizard

# Compile FreePBX module translation files (.po to .mo)
# Only compile files in proper i18n/LC_MESSAGES directories, skip vendor/test directories
RUN find /var/www/html/freepbx/admin -path "*/i18n/*/LC_MESSAGES/*.po" -exec sh -c 'msgfmt -o "${1%.po}.mo" "$1" 2>/dev/null || true' _ {} \;

# enable apache rewrite module
RUN a2enmod rewrite proxy* headers

# disable server-status page
RUN a2dismod status

# Upgrade Apache to latest version to get security fixes
RUN apt-get update && apt-get install -y --only-upgrade apache2 && rm -rf /var/lib/apt/lists/*

# Clean apt files
RUN apt-get clean autoclean && apt-get autoremove --yes && rm -rf /var/lib/{apt,dpkg,cache,log}/* && touch /var/lib/dpkg/status

# Rotate logs hourly
RUN mv /etc/cron.daily/logrotate /etc/cron.hourly/logrotate

# Install centralized phonebook update script and CSV upload path
COPY usr/share/phonebooks /usr/share/phonebooks
RUN mkdir -p /var/lib/nethvoice/phonebook/uploads \
	&& touch /var/lib/nethvoice/phonebook/uploads/.nethvoice-volume-guard \
	&& chown -R asterisk:asterisk /var/lib/nethvoice/phonebook/uploads

# Overwrite Debian default vim mouse policy
RUN echo "source \$VIMRUNTIME/defaults.vim\nset mouse-=a" >> /root/.vimrc

COPY etc/apache2/sites-enabled/000-default.conf /etc/apache2/sites-enabled/000-default.conf
COPY etc/supervisor/conf.d/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY freepbx_init.sh /freepbx_init.sh
COPY etc/amportal.conf /etc
COPY initdb.d/initdb.php /initdb.d/
COPY initdb.d/migration.php /initdb.d/
COPY etc/logrotate.d/asterisk /etc/logrotate.d/asterisk
COPY initdb.d/update.php /initdb.d/
COPY initdb.d/slow_database_updates.php /initdb.d/
COPY usr/src/nethvoice/samples/* /usr/src/nethvoice/samples/
COPY configure_users.php /
COPY entrypoint.sh /entrypoint
COPY usr/share/neth-hotel-fias /usr/share/neth-hotel-fias
CMD ["/usr/bin/supervisord"]
ENTRYPOINT ["/entrypoint"]
