FROM docker.io/library/node:24.11.1-slim as node_builder
WORKDIR /app
# install deps
COPY package.json .
COPY yarn.lock .
RUN --mount=type=cache,id=nethvoice-ui-yarn,target=/var/cache/yarn \
    yarn install --frozen-lockfile --cache-folder /var/cache/yarn
# copy application
COPY public public
COPY src src
COPY .browserslistrc .
COPY .eslintrc.js .
COPY babel.config.js .
COPY vue.config.js .
# build application
ENV NODE_OPTIONS=--openssl-legacy-provider
RUN yarn build

FROM scratch as dist
COPY --from=node_builder /app/dist /
