#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import subprocess
import agent

timezones_directory = "/usr/share/zoneinfo/posix/"
command = "find *  -type f -or -type l"
# Get the list of timezones
accepted_timezone_list = subprocess.check_output(command, cwd=timezones_directory, text=True, shell=True).splitlines()

# Get proxy status
rdb = agent.redis_connect(privileged=True)
proxy_id = agent.resolve_agent_id('nethvoice-proxy@node')
proxy_status = {
    "proxy_installed": True if proxy_id is not None else False,
}

if (proxy_id is not None):
    proxy_id = proxy_id.split("module/")[1]
    proxy_status["module_id"] = proxy_id

config={
        "accepted_timezone_list": accepted_timezone_list,
        "proxy_status": proxy_status,
        }

json.dump(config, fp=sys.stdout)
