#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import subprocess

mariadb_root_passwd = agent.read_envfile("passwords.env")['MARIADB_ROOT_PASSWORD']

request = json.load(sys.stdin)

# change password in asterisk database if it isn't empty
if request['nethvoice_admin_password']:

	command = [
    	"/usr/bin/podman", "exec", "-it", "mariadb",
    	"mysql", "-uroot", f"-p{mariadb_root_passwd}", "asterisk",
    	"-e",
    	f"UPDATE ampusers SET password_sha1 = SHA1('{request['nethvoice_admin_password']}') WHERE username = 'admin';"
	]

	result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
	if result.returncode != 0:
		print(f"Failed to execute command: {result.stderr}")
		sys.exit(1)

# change password in sftpgo configuration
result = subprocess.run(["bin/set-sftp-config"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
if result.returncode != 0:
	print(f"Failed to execute command: {result.stderr}")
	sys.exit(1)

sys.exit(0)

