#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e -o pipefail
exec 1>&2 # Redirect any output to the journal (stderr)

SATELLITE_PGSQL_PASSWORD=$(grep '^SATELLITE_PGSQL_PASSWORD=' ./passwords.env) && export "${SATELLITE_PGSQL_PASSWORD?}"

mkdir -vp restore
cat - >restore/satellite_postgresql_restore.sh <<'EOS'
# Read dump file from standard input and restore all databases:
psql -U postgres -f /tmp/satellite_postgresql.pg_dump
ec=$?
docker_temp_server_stop
exit $ec
EOS

# Override the image /docker-entrypoint-initdb.d contents, to restore the
# DB dump file. The container will be stopped at the end
podman run \
    --rm \
    --interactive \
    --network=none \
    --volume=./restore:/docker-entrypoint-initdb.d/:Z \
    --volume=satellite_pgdata:/var/lib/postgresql/data:Z \
    --volume=./satellite_postgresql.pg_dump:/tmp/satellite_postgresql.pg_dump:Z \
    --replace --name=restore_db \
    --env POSTGRES_USER=${SATELLITE_PGSQL_USER} \
    --env POSTGRES_PASSWORD=${SATELLITE_PGSQL_PASSWORD} \
    --env TZ=UTC \
    "${POSTGRES_IMAGE}"


# If the restore is successful, clean up:
rm -rfv restore/ postgresql.pg_dump